'use client';
import { flushSync } from 'react-dom';
import { useEffect, useReducer, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Clock3, Crosshair, Grid3X3, House, MapPin, Move, MoveHorizontal, Pentagon, RotateCcw, RotateCw, Ruler, ScanLine, Trophy } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import GameBoard from '@/components/game-board';
import LeaderboardPanel from '@/components/leaderboard-panel';
import ScoreUpload from '@/components/score-upload';
import { GAME_TIME_LIMIT_SECONDS, elapsedSeconds, gameIds, makeQuestions, reducer, score, startSession, type GameId, type Question } from '@/lib/game';
import { fetchPersonalBests, formatDuration, hubUrl, leaderboardUrl, validStudent, type ClassName, type PersonalBest } from '@/lib/leaderboard';

const games=[
 {title:'讀寫坐標',label:'先橫後直',text:'從坐標圖讀出點的位置，寫成完整坐標。',sample:'A → (−3, 4)',icon:MapPin,color:'green'},
 {title:'標示位置',label:'精準落點',text:'根據給定坐標，在坐標平面上標點。',sample:'P(2, −5)',icon:Crosshair,color:'blue'},
 {title:'認識象限',label:'四區導航',text:'分辨四個象限、坐標軸及原點。',sample:'(−2, 3) → 象限 II',icon:Grid3X3,color:'amber'},
 {title:'水平線與鉛垂線',label:'橫直規律',text:'辨認水平與鉛垂線上不變的坐標。',sample:'同一水平線 → y 相同',icon:ScanLine,color:'red'},
 {title:'兩點距離',label:'量度格點',text:'計算水平或鉛垂線上兩點的距離。',sample:'|5 − (−2)| = 7',icon:Ruler,color:'cyan'},
 {title:'面積建築師',label:'分割與補形',text:'利用頂點坐標計算多邊形面積。',sample:'面積＝底 × 高 ÷ 2',icon:Pentagon,color:'orange'},
 {title:'平移',label:'沿軸移動',text:'找出水平及鉛垂平移後的坐標。',sample:'(x, y) → (x＋3, y)',icon:Move,color:'green'},
 {title:'反射',label:'鏡像坐標',text:'找出對水平或鉛垂直線反射的影像。',sample:'對 x 軸：(x, y) → (x, −y)',icon:MoveHorizontal,color:'blue'},
 {title:'旋轉',label:'繞原點轉動',text:'找出繞原點旋轉後的影像坐標。',sample:'180°：(x, y) → (−x, −y)',icon:RotateCw,color:'amber'},
] as const;
export default function Home(){
 const[session,dispatch]=useReducer(reducer,null),[now,setNow]=useState(0),[uploaded,setUploaded]=useState(false),[showLeaderboard,setShowLeaderboard]=useState(false),[lastStudent,setLastStudent]=useState<{className:ClassName;studentNo:number}>(),[personalBests,setPersonalBests]=useState<Partial<Record<GameId,PersonalBest>>>({}),[personalBestStatus,setPersonalBestStatus]=useState<'none'|'loading'|'ready'|'error'>('none');
 const previous=useRef<Partial<Record<GameId,Question[]>>>({}),connected=Boolean(leaderboardUrl);
 const start=(game:GameId)=>{const questions=makeQuestions(game,previous.current[game]);previous.current[game]=questions;const next=startSession(game,questions);setUploaded(false);setShowLeaderboard(false);setNow(next.startedAt);dispatch({type:'start',session:next})};
 const goHome=()=>{if(session?.finished&&!session.expired&&connected&&!uploaded)return;dispatch({type:'home'});setShowLeaderboard(false)};
 useEffect(()=>{if(!session||session.finished)return;const timer=setInterval(()=>{const current=Date.now();setNow(current);if(elapsedSeconds(session,current)>=GAME_TIME_LIMIT_SECONDS)dispatch({type:'timeout'})},1000);return()=>clearInterval(timer)},[session]);
 useEffect(()=>{const query=new URLSearchParams(window.location.search),schoolYear=query.get('schoolYear')||'',className=query.get('className')||'',studentNo=Number(query.get('studentNo'));if(!schoolYear||!validStudent(className,studentNo))return;void Promise.resolve().then(()=>setPersonalBestStatus('loading'));void fetchPersonalBests({schoolYear,className:className as ClassName,studentNo}).then(response=>{if(!response.ok)throw new Error(response.message||'讀取失敗');setPersonalBests(Object.fromEntries(response.bests.map(best=>[best.gameId,best])));setPersonalBestStatus('ready')}).catch(()=>setPersonalBestStatus('error'))},[]);
 useEffect(()=>{type Tool={name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown};const context=(document as Document&{modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();try{void Promise.resolve(context.registerTool({name:'start_coordinate_game',description:'Start a Form 1 coordinate geometry practice game.',inputSchema:{type:'object',properties:{game:{type:'string',enum:gameIds}},required:['game'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){if(!input||typeof input!=='object'||!('game'in input)||!gameIds.includes(input.game as GameId))throw new Error(`Choose one of: ${gameIds.join(', ')}.`);const game=input.game as GameId;flushSync(()=>start(game));return{game,question:1,totalQuestions:15}}},{signal:controller.signal})).catch(()=>undefined)}catch{}return()=>controller.abort()},[]);
 const active=session?games[gameIds.indexOf(session.game)]:null,elapsed=session?elapsedSeconds(session,now):0,time=`${String(Math.floor(elapsed/60)).padStart(2,'0')}:${String(elapsed%60).padStart(2,'0')}`;
 return <main className={`world ${session||showLeaderboard?'playing':''}`}><header className="topbar"><a className="hub-home" href={hubUrl}><House/>返回主畫面</a><button className="brand" disabled={Boolean(session?.finished&&!session.expired&&connected&&!uploaded)} onClick={goHome}><span className="brand-icon"><Grid3X3/></span>坐標方塊世界</button><span className="top-note">中一數學 · 坐標幾何</span></header>
 {showLeaderboard&&!session?<LeaderboardPanel onClose={()=>setShowLeaderboard(false)} student={lastStudent}/>:!session?<section className="menu"><div className="menu-heading"><span className="eyebrow">準備好，出發探索！</span><h1>選一個世界，<br/>開始你的數學冒險。</h1><p>九個小遊戲，自由選擇，學會中一坐標幾何。</p><Button className="block-btn leaderboard-button" onClick={()=>setShowLeaderboard(true)}><Trophy/>查看排行榜</Button></div><div className="game-grid coordinate-game-grid">{games.map((game,index)=>{const best=personalBests[gameIds[index]];return <Button key={game.title} className={`game-card ${game.color}`} onClick={()=>start(gameIds[index])}><span className="card-top"><span className="game-icon"><game.icon/></span><span className="game-number">{String(index+1).padStart(2,'0')}</span></span><span className="card-label">{game.label}</span><h2>{game.title}</h2><span className="card-copy">{game.text}</span><span className="sample">{game.sample}</span>{personalBestStatus!=='none'&&<span className={`personal-best-card ${personalBestStatus}`}>{personalBestStatus==='loading'?'讀取紀錄中……':personalBestStatus==='error'?'紀錄暫未能讀取':best?`個人最佳 ${best.score} 分 · ${formatDuration(best.elapsedSeconds)}`:'尚未挑戰'}</span>}<span className="card-bottom"><span><Clock3/>約 10 分鐘</span><span>進入遊戲 <ArrowRight/></span></span></Button>})}</div><footer className="menu-footer"><span>自由選關 · 隨時重玩</span></footer></section>:
 <section className={`play-area ${active?.color}`}><div className="play-nav"><Button variant="secondary" className="block-btn secondary" disabled={Boolean(session.finished&&!session.expired&&connected&&!uploaded)} onClick={goHome}><ArrowLeft/>返回選關</Button><div className="play-name">{active&&<active.icon/>}<h1>{active?.title}</h1></div><span className="elapsed"><Clock3/>已練習 {time}</span></div>{session.finished?<div className="game-panel finish"><div className="finish-check"><Check/></div><span className="task-label">{session.expired?'時間到':'這次探索完成了'}</span><h2>{session.expired?'遊戲時間已結束':'每一步，都更有把握。'}</h2><p>{session.expired?`本局已達 1 小時時間限制，已完成 ${session.index+Number(session.solved)} 題。未完成的局數不會上傳排行榜。`:`你完成了「${active?.title}」的全部 ${session.questions.length} 個任務。`}</p><div className="final-score"><span>本次得分</span><strong>{score(session)}<small> / {session.questions.length*10} 分</small></strong></div><div className="result-grid"><div><strong>{session.firstTry}</strong><span>首次作答全對</span></div><div><strong>{(session.expired?session.index+Number(session.solved):session.questions.length)-session.firstTry-session.skipped}</strong><span>重試後答對</span></div><div><strong>{time}</strong><span>遊戲時間</span></div></div><p className="result-note">每題首次全對 10 分，重試後完成 5 分；放棄 {session.skipped} 題不計分。</p>{!session.expired&&<ScoreUpload gameId={session.game} score={score(session)} maxScore={session.questions.length*10} elapsedSeconds={elapsed} questionCount={session.questions.length} firstTryCorrect={session.firstTry} skippedQuestions={session.skipped} longestFirstTryStreak={session.longestFirstTryStreak} wrongAttempts={session.errors} onUploaded={(identity,best)=>{setUploaded(true);setLastStudent(identity);if(best){setPersonalBests(current=>({...current,[session.game]:best}));setPersonalBestStatus('ready')}}}/>}<div className="answer-options"><Button className="block-btn" disabled={connected&&!uploaded&&!session.expired} onClick={()=>start(session.game)}><RotateCcw/>再玩一次</Button><Button className="block-btn secondary" variant="secondary" disabled={connected&&!uploaded&&!session.expired} onClick={goHome}>選其他遊戲<ArrowRight/></Button></div></div>:<div className="game-panel"><div className="round-top"><span>任務 <b>{String(session.index+1).padStart(2,'0')}</b> / {session.questions.length}</span><span className="live-score">得分 <b>{score(session)}</b> / {session.questions.length*10}</span><span>5 基礎 · 5 核心 · 5 綜合</span></div><Progress aria-label="本局已完成任務" value={(session.index+(session.solved?1:0))/session.questions.length*100}/><GameBoard key={`${session.game}-${session.startedAt}-${session.index}`} session={session} answer={value=>dispatch({type:'answer',value})} skip={()=>dispatch({type:'skip'})}/><div className="round-bottom">{elapsed>=600&&<span>已練習 10 分鐘，你可以繼續或返回選關。</span>}{session.solved&&<Button className="block-btn" onClick={()=>dispatch({type:'next'})}>{session.index===session.questions.length-1?'查看本次結果':'下一個任務'}<ArrowRight/></Button>}</div></div>}</section>}</main>
}
