import test from'node:test';import assert from'node:assert/strict';
import{GAME_TIME_LIMIT_SECONDS,elapsedSeconds,expireSession,gameIds,makeQuestions,nextQuestion,questionKey,score,skipQuestion,startSession,submit}from'../lib/game.ts';
const answerFor=q=>q.kind==='coordinate'?(q.input==='plot'?`${q.answer.x},${q.answer.y}`:`(${q.answer.x}, ${q.answer.y})`):String(q.answer);
test('coordinate world contains the nine approved stages',()=>assert.deepEqual(gameIds,['read-coordinates','plot-points','quadrants','horizontal-vertical','distance','area','translation','reflection','rotation']));
test('every stage generates distinct 5-5-5 questions',()=>{for(const game of gameIds)for(let run=0;run<30;run++){const questions=makeQuestions(game);assert.equal(questions.length,15);assert.equal(new Set(questions.map(questionKey)).size,15);questions.forEach((q,index)=>assert.equal(q.level,Math.floor(index/5)))}});
test('replays avoid all questions from the previous round',()=>{for(const game of gameIds){const first=makeQuestions(game),second=makeQuestions(game,first),old=new Set(first.map(questionKey));second.forEach(q=>assert.equal(old.has(questionKey(q)),false,`${game}: repeated question`))}});
test('all generated intended answers complete a perfect session',()=>{for(const game of gameIds){let session=startSession(game);while(!session.finished){session=submit(session,answerFor(session.questions[session.index]));assert.equal(session.solved,true,`${game}: ${session.feedback}`);if(!session.finished)session=nextQuestion(session)}assert.equal(session.firstTry,15);assert.equal(score(session),150)}});
test('coordinate writing requires brackets and comma',()=>{const question={kind:'coordinate',level:0,variant:0,prompt:'',instruction:'',answer:{x:-3,y:4},input:'text',hints:['提示'],points:[]};let session=startSession('read-coordinates',[question]);session=submit(session,'-3 4');assert.equal(session.solved,false);assert.equal(session.errors,1);assert.match(session.feedback,/格式/);session=submit(session,'（−3，4）');assert.equal(session.solved,true);assert.equal(score(session),5)});
test('comprehensive coordinate stages include the origin and both axes',()=>{for(const game of['read-coordinates','plot-points']){const answers=makeQuestions(game).filter(q=>q.level===2).map(q=>q.answer);assert.ok(answers.some(p=>p.x===0&&p.y===0));assert.ok(answers.some(p=>p.x===0&&p.y!==0));assert.ok(answers.some(p=>p.y===0&&p.x!==0))}});
test('quadrant core questions contain exactly one matching point',()=>{for(let run=0;run<100;run++)for(const q of makeQuestions('quadrants').filter(q=>q.level===1)){const quadrant=q.prompt.match(/象限 (?:IV|III|II|I)/)?.[0];const matching=q.points.filter(p=>p.x>0&&p.y>0&&quadrant==='象限 I'||p.x<0&&p.y>0&&quadrant==='象限 II'||p.x<0&&p.y<0&&quadrant==='象限 III'||p.x>0&&p.y<0&&quadrant==='象限 IV');assert.equal(matching.length,1,q.prompt);assert.deepEqual(q.choices,['A','B','C','D']);assert.equal(q.points.find(p=>p.label===q.answer)?.x,matching[0].x);assert.equal(q.points.find(p=>p.label===q.answer)?.y,matching[0].y)}});
test('quadrant core and comprehensive formats are swapped and all choices stay fixed',()=>{const questions=makeQuestions('quadrants'),basic=questions.filter(q=>q.level===0),core=questions.filter(q=>q.level===1),comprehensive=questions.filter(q=>q.level===2);basic.forEach(q=>assert.deepEqual(q.choices,['象限 I','象限 II','象限 III','象限 IV']));core.forEach(q=>assert.match(q.prompt,/^哪一點位於象限 (?:IV|III|II|I)？$/));comprehensive.forEach(q=>{assert.match(q.prompt,/^點 /);assert.deepEqual(q.choices,['象限 I','象限 II','象限 III','象限 IV','x 軸','y 軸','原點'])});for(let run=0;run<30;run++){makeQuestions('horizontal-vertical').filter(q=>q.kind==='choice').forEach(q=>assert.deepEqual(q.choices,q.choices.length===2?['水平線','鉛垂線']:['水平線','鉛垂線','兩者皆非']))}});
test('comprehensive translations change both coordinates and core reflections mix both axes',()=>{for(let run=0;run<60;run++){for(const q of makeQuestions('translation').filter(q=>q.level===2)){const original=q.points[0];assert.notEqual(q.answer.x,original.x);assert.notEqual(q.answer.y,original.y)}const core=makeQuestions('reflection').filter(q=>q.level===1);assert.ok(core.some(q=>q.prompt.includes('x 軸')));assert.ok(core.some(q=>q.prompt.includes('y 軸')))}});
test('plot answers use a selected grid point and empty submissions do not count as errors',()=>{const question={kind:'coordinate',level:0,variant:0,prompt:'',instruction:'',answer:{x:2,y:-5},input:'plot',hints:['提示']};let session=startSession('plot-points',[question]);session=submit(session,'');assert.equal(session.errors,0);session=submit(session,'2,-5');assert.equal(session.solved,true)});
test('distance and area stay within the approved range',()=>{for(let run=0;run<100;run++){for(const q of makeQuestions('distance'))if(q.kind==='numeric'&&q.suffix.includes('單位'))assert.ok(q.answer>=-8&&q.answer<=16);for(const q of makeQuestions('area')){assert.equal(q.kind,'numeric');assert.ok(q.answer>0&&q.answer<=256);assert.equal(Number.isInteger(q.answer*2),true)}}});
test('reflection and rotation images remain inside the grid',()=>{for(const game of['reflection','rotation'])for(let run=0;run<100;run++)for(const q of makeQuestions(game)){assert.equal(q.kind,'coordinate');assert.ok(Math.abs(q.answer.x)<=8&&Math.abs(q.answer.y)<=8,`${game}: ${JSON.stringify(q.answer)}`)}});
test('errors, retries, comprehensive skips and timer retain the shared rules',()=>{const questions=Array.from({length:15},(_,i)=>({kind:'numeric',level:Math.floor(i/5),variant:i%5,prompt:'',instruction:'',answer:i+1,suffix:'',hints:['提示']}));let session=startSession('distance',questions,1000);session=submit(session,'99');session=submit(session,'1');assert.equal(score(session),5);for(let i=1;i<10;i++){session=nextQuestion(session);session=submit(session,String(i+1))}session=nextQuestion(session);session=skipQuestion(session);assert.equal(session.skipped,1);while(!session.finished){session=nextQuestion(session);session=submit(session,String(session.index+1),6500)}assert.equal(elapsedSeconds(session,90000),5)});
test('sessions expire after one hour without uploading an unfinished score',()=>{const session=startSession('quadrants',makeQuestions('quadrants').slice(0,2),1000),expired=expireSession(session,1000+GAME_TIME_LIMIT_SECONDS*1000);assert.equal(expired.finished,true);assert.equal(expired.expired,true);assert.match(expired.feedback,/1 小時/)});

test('every rotation round has exactly three comprehensive 270 degree questions',()=>{let previous=[];for(let run=0;run<100;run++){const questions=makeQuestions('rotation',previous),comprehensive=questions.filter(q=>q.level===2),turns=comprehensive.filter(q=>q.prompt.includes('逆時針 270°'));assert.equal(turns.length,3);for(const q of turns){const p=q.points[0];assert.deepEqual(q.answer,{x:p.y,y:-p.x})}previous=questions}});
