'use client';
import { useEffect, useReducer, useRef, useState } from 'react';
import { flushSync } from 'react-dom';
import { ArrowLeft, ArrowRight, Check, Clock3, Compass, Gem, House, Mountain, Pickaxe, RotateCcw, ScanSearch, Square, Trophy } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import GameBoard, { MathText } from '@/components/game-board';
import LeaderboardPanel from '@/components/leaderboard-panel';
import ScoreUpload from '@/components/score-upload';
import { elapsedSeconds, GAME_TIME_LIMIT_SECONDS, gameIds, reducer, score, startSession, type GameId, type Question } from '@/lib/game';
import { replayQuestions } from '@/lib/replay';
import { fetchPersonalBests, formatDuration, hubUrl, leaderboardUrl, validStudent, type ClassName, type PersonalBest } from '@/lib/leaderboard';

const games=[
 {title:'恆等式辨識',label:'辨真入口',text:'比較左右兩方，判斷是否對所有值成立。',sample:'2(x ＋ 3) ≡ 2x ＋ 6',icon:ScanSearch,color:'green'},
 {title:'未知常數',label:'岩紋解碼',text:'展開及比較係數，找出指定常數。',sample:'Ax ＋ B ≡ 3x ＋ 2',icon:Gem,color:'blue'},
 {title:'平方差',label:'裂谷開拓',text:'認識共軛因式，運用平方差展開。',sample:'(x ＋ 3)(x − 3)＝x² − 9',icon:Pickaxe,color:'amber'},
 {title:'和的完全平方',label:'方岩建築',text:'留意中間項，展開兩項和的平方。',sample:'(x ＋ 2)²＝x² ＋ 4x ＋ 4',icon:Square,color:'red'},
 {title:'差的完全平方',label:'岩壁雕刻',text:'掌握正負號，展開兩項差的平方。',sample:'(x − 2)²＝x² − 4x ＋ 4',icon:Mountain,color:'cyan'},
 {title:'恆等式綜合應用',label:'峽谷探險',text:'選用恆等式，完成速算與綜合化簡。',sample:'29 × 31＝30² − 1',icon:Compass,color:'orange'},
] as const;

export default function Home(){
 const [session,dispatch]=useReducer(reducer,null),[now,setNow]=useState(0),[uploaded,setUploaded]=useState(false),[showLeaderboard,setShowLeaderboard]=useState(false),[lastStudent,setLastStudent]=useState<{className:ClassName;studentNo:number}>(),[personalBests,setPersonalBests]=useState<Partial<Record<GameId,PersonalBest>>>({}),[personalBestStatus,setPersonalBestStatus]=useState<'none'|'loading'|'ready'|'error'>('none');
 const previous=useRef<Partial<Record<GameId,Question[]>>>({}),connected=Boolean(leaderboardUrl);
 const start=(game:GameId)=>{let storage:Storage|undefined;try{storage=window.sessionStorage}catch{}const questions=replayQuestions(game,window.location.search,storage,previous.current[game]);previous.current[game]=questions;const next=startSession(game,questions);setUploaded(false);setShowLeaderboard(false);setNow(next.startedAt);dispatch({type:'start',session:next})};
 const goHome=()=>{if(session?.finished&&!session.expired&&connected&&!uploaded)return;dispatch({type:'home'});setShowLeaderboard(false)};
 useEffect(()=>{if(!session||session.finished)return;const timer=setInterval(()=>{const current=Date.now();setNow(current);if(elapsedSeconds(session,current)>=GAME_TIME_LIMIT_SECONDS)dispatch({type:'timeout'})},1000);return()=>clearInterval(timer)},[session]);
 useEffect(()=>{const query=new URLSearchParams(window.location.search),schoolYear=query.get('schoolYear')||'',className=query.get('className')||'',studentNo=Number(query.get('studentNo'));if(!schoolYear||!validStudent(className,studentNo))return;void Promise.resolve().then(()=>setPersonalBestStatus('loading'));void fetchPersonalBests({schoolYear,className:className as ClassName,studentNo}).then(response=>{if(!response.ok)throw new Error(response.message||'讀取失敗');setPersonalBests(Object.fromEntries(response.bests.map(best=>[best.gameId,best])));setPersonalBestStatus('ready')}).catch(()=>setPersonalBestStatus('error'))},[]);
 useEffect(()=>{type Tool={name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown};const context=(document as Document&{modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();try{void Promise.resolve(context.registerTool({name:'start_identity_game',description:'Start a new Form 1 identity practice game.',inputSchema:{type:'object',properties:{game:{type:'string',enum:gameIds}},required:['game'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){if(!input||typeof input!=='object'||!('game'in input)||!gameIds.includes(input.game as GameId)||Object.keys(input).length!==1)throw new Error(`Choose one of: ${gameIds.join(', ')}.`);const game=input.game as GameId;flushSync(()=>start(game));return{game,question:1,totalQuestions:15}}},{signal:controller.signal})).catch(()=>undefined)}catch{}return()=>controller.abort()},[]);
 const active=session?games[gameIds.indexOf(session.game)]:null,elapsed=session?elapsedSeconds(session,now):0,time=`${String(Math.floor(elapsed/60)).padStart(2,'0')}:${String(elapsed%60).padStart(2,'0')}`;
 return <main className={`world ${session||showLeaderboard?'playing':''}`}>
  <header className="topbar"><a className="hub-home" href={hubUrl}><House/>返回主畫面</a><button className="brand" disabled={Boolean(session?.finished&&!session.expired&&connected&&!uploaded)} onClick={goHome}><span className="brand-icon"><Mountain/></span>恆等式方塊世界</button><span className="top-note">中一數學 · 恆等式</span></header>
  {showLeaderboard&&!session?<LeaderboardPanel onClose={()=>setShowLeaderboard(false)} student={lastStudent}/>:!session?<section className="menu"><div className="menu-heading"><span className="eyebrow">準備好，出發探索！</span><h1>選一個世界，<br/>開始你的數學冒險。</h1><p>六個小遊戲，自由選擇，探索中一恆等式峽谷。</p><Button className="block-btn leaderboard-button" onClick={()=>setShowLeaderboard(true)}><Trophy/>查看排行榜</Button></div><div className="game-grid">{games.map((game,index)=>{const best=personalBests[gameIds[index]];return <Button key={game.title} className={`game-card ${game.color}`} onClick={()=>start(gameIds[index])}><span className="card-top"><span className="game-icon"><game.icon/></span><span className="game-number">0{index+1}</span></span><span className="card-label">{game.label}</span><h2>{game.title}</h2><span className="card-copy">{game.text}</span><span className="sample"><MathText>{game.sample}</MathText></span>{personalBestStatus!=='none'&&<span className={`personal-best-card ${personalBestStatus}`}>{personalBestStatus==='loading'?'讀取紀錄中……':personalBestStatus==='error'?'紀錄暫未能讀取':best?`個人最佳 ${best.score} 分 · ${formatDuration(best.elapsedSeconds)}`:'尚未挑戰'}</span>}<span className="card-bottom"><span><Clock3/>約 10 分鐘</span><span>進入遊戲 <ArrowRight/></span></span></Button>})}</div><footer className="menu-footer"><span>自由選關 · 隨時重玩</span></footer></section>:
  <section className={`play-area ${active?.color}`}><div className="play-nav"><Button variant="secondary" className="block-btn secondary" disabled={Boolean(session.finished&&!session.expired&&connected&&!uploaded)} onClick={goHome}><ArrowLeft/>返回選關</Button><div className="play-name">{active&&<active.icon/>}<h1>{active?.title}</h1></div><span className="elapsed"><Clock3/>已練習 {time}</span></div>
   {session.finished?<div className="game-panel finish"><div className="finish-check"><Check/></div><span className="task-label">{session.expired?'時間到':'這次探索完成了'}</span><h2>{session.expired?'遊戲時間已結束':'每一步，都更有把握。'}</h2><p>{session.expired?`本局已達 1 小時時間限制，已完成 ${session.index+Number(session.solved)} 題；本局不會上傳排行榜或計算襟章。`:`你完成了「${active?.title}」的全部 ${session.questions.length} 個任務。`}</p><div className="final-score"><span>本次得分</span><strong>{score(session)}<small> / {session.questions.length*10} 分</small></strong></div><div className="result-grid"><div><strong>{session.firstTry}</strong><span>首次作答全對</span></div><div><strong>{(session.expired?session.index+Number(session.solved):session.questions.length)-session.firstTry-session.skipped}</strong><span>重試後答對</span></div><div><strong>{time}</strong><span>遊戲時間</span></div></div><p className="result-note">每題首次全對 10 分，重試後完成 5 分；放棄 {session.skipped} 題不計分。</p>{!session.expired&&<ScoreUpload gameId={session.game} score={score(session)} maxScore={session.questions.length*10} elapsedSeconds={elapsed} questionCount={session.questions.length} firstTryCorrect={session.firstTry} skippedQuestions={session.skipped} longestFirstTryStreak={session.longestFirstTryStreak} wrongAttempts={session.errors} onUploaded={(identity,best)=>{setUploaded(true);setLastStudent(identity);if(best){setPersonalBests(current=>({...current,[session.game]:best}));setPersonalBestStatus('ready')}}}/>}<div className="answer-options"><Button className="block-btn" disabled={connected&&!uploaded&&!session.expired} onClick={()=>start(session.game)}><RotateCcw/>再玩一次</Button><Button className="block-btn secondary" variant="secondary" disabled={connected&&!uploaded&&!session.expired} onClick={goHome}>選其他遊戲<ArrowRight/></Button></div></div>:
   <div className="game-panel"><div className="round-top"><span>任務 <b>{String(session.index+1).padStart(2,'0')}</b> / {session.questions.length}</span><span className="live-score">得分 <b>{score(session)}</b> / {session.questions.length*10}</span><span>5 基礎 · 5 核心 · 5 綜合</span></div><Progress aria-label="本局已完成任務" value={(session.index+(session.solved?1:0))/session.questions.length*100}/><GameBoard key={`${session.game}-${session.startedAt}-${session.index}`} session={session} answer={value=>dispatch({type:'answer',value})} skip={()=>dispatch({type:'skip'})}/><div className="round-bottom">{elapsed>=600&&<span>已練習 10 分鐘，你可以繼續或返回選關。</span>}{session.solved&&<Button className="block-btn" onClick={()=>dispatch({type:'next'})}>{session.index===session.questions.length-1?'查看本次結果':'下一個任務'}<ArrowRight/></Button>}</div></div>}
  </section>}
 </main>;
}
