'use client';
import {useEffect,useMemo,useState} from 'react';
import {BookOpen,Braces,Calculator,ChevronRight,Equal,Percent,RefreshCcw,Shield,UserRound} from 'lucide-react';
import {algebraUrl,identityUrl,coordinateUrl,percentageUrl,directedUrl,equationUrl,polynomialUrl,numericalEstimationUrl,fetchConfig,fetchProfile,gameUrl,platformUrl,storageKey,validIdentity,type Badge,type Config,type Identity,type Profile} from '@/lib/platform';

const fallbackConfig:Config={ok:true,schoolYear:'',classes:['1A','1B','1C','1D'],studentNoMin:1,studentNoMax:33};
const filters=[['all','全部'],['earned','已取得'],['unearned','未取得'],['stage','單一關卡'],['perfect','滿分'],['skill','技術'],['cumulative','累積'],['exploration','探索']] as const;
export default function Home(){
 const [config,setConfig]=useState<Config>(fallbackConfig),[identity,setIdentity]=useState<Identity|null>(()=>{if(typeof window==='undefined')return null;const saved=sessionStorage.getItem(storageKey);if(!saved)return null;try{return JSON.parse(saved) as Identity}catch{return null}}),[profile,setProfile]=useState<Profile|null>(null),[className,setClassName]=useState(''),[studentNo,setStudentNo]=useState(''),[filter,setFilter]=useState<(typeof filters)[number][0]>('all'),[configLoading,setConfigLoading]=useState(true),[profileLoading,setProfileLoading]=useState(Boolean(identity)),[refreshToken,setRefreshToken]=useState(0),[message,setMessage]=useState('');
 const loading=configLoading||profileLoading;
 useEffect(()=>{fetchConfig().then(next=>{if(!next.ok)throw new Error('未能讀取平台設定。');setConfig(next);const saved=sessionStorage.getItem(storageKey);if(saved){try{const student=JSON.parse(saved) as Identity;if(student.schoolYear!==next.schoolYear||!validIdentity(next,student.className,student.studentNo)){sessionStorage.removeItem(storageKey);setIdentity(null);setProfileLoading(false)}}catch{sessionStorage.removeItem(storageKey);setIdentity(null);setProfileLoading(false)}}}).catch(()=>setMessage(platformUrl?'暫時未能連接收藏系統，請稍後重新整理。':'收藏系統尚未連接；部署後才會顯示學生進度。')).finally(()=>setConfigLoading(false))},[]);
 useEffect(()=>{if(!identity||configLoading)return;let active=true;fetchProfile(identity).then(next=>{if(!next.ok)throw new Error(next.message||'未能讀取收藏。');if(active){setProfile(next);setMessage('')}}).catch(e=>{if(active)setMessage(e instanceof Error?e.message:'未能讀取收藏。')}).finally(()=>{if(active)setProfileLoading(false)});return()=>{active=false}},[identity,configLoading,refreshToken]);
 const choose=()=>{const no=Number(studentNo);if(!config.schoolYear||!validIdentity(config,className,no))return;const next={schoolYear:config.schoolYear,className,studentNo:no};sessionStorage.setItem(storageKey,JSON.stringify(next));setProfile(null);setProfileLoading(true);setIdentity(next);setMessage('')};
 const switchStudent=()=>{sessionStorage.removeItem(storageKey);setIdentity(null);setProfile(null);setProfileLoading(false);setClassName('');setStudentNo('')};
 const refresh=()=>{if(identity){setProfileLoading(true);setRefreshToken(current=>current+1)}};
 const badges=useMemo(()=>profile?.badges.filter(b=>filter==='all'||filter==='earned'&&b.earned||filter==='unearned'&&!b.earned||b.category===filter)||[],[profile,filter]);
 if(!identity)return <main className="world"><header><span className="logo"><Calculator/></span><strong>中一數學方塊世界</strong><span>課堂鞏固 · 襟章收藏</span></header><section className="identity-card"><span className="eyebrow">選擇你的冒險身份</span><h1>準備進入方塊世界</h1><p>學年由老師設定。身份只會保留在這個瀏覽器分頁。</p><div className="identity-fields"><label>學年<input value={config.schoolYear||'等待連接'} disabled/></label><label>班別<select value={className} onChange={e=>setClassName(e.target.value)}><option value="">請選擇</option>{config.classes.map(c=><option key={c}>{c}</option>)}</select></label><label>學號<input inputMode="numeric" placeholder={`${config.studentNoMin} 至 ${config.studentNoMax}`} value={studentNo} onChange={e=>/^\d{0,2}$/.test(e.target.value)&&setStudentNo(e.target.value)}/></label></div><button className="block-button" disabled={!config.schoolYear||!validIdentity(config,className,Number(studentNo))} onClick={choose}><UserRound/>查看我的世界</button>{loading&&<p className="notice">正在連接……</p>}{message&&<p className="notice error">{message}</p>}</section></main>;
 return <main className="world dashboard"><header><span className="logo"><Calculator/></span><strong>中一數學方塊世界</strong><span>{identity.schoolYear}　{identity.className} 班　{identity.studentNo} 號</span><button onClick={switchStudent}>更換學生</button></header><section className="content"><div className="summary"><div><span className="eyebrow">我的收藏進度</span><h1>{identity.className} 班　{identity.studentNo} 號</h1><p>完成不同關卡，逐步建立你的數學收藏。</p></div><div className="summary-stats"><span><strong>{profile?.summary.earnedBadges??0}</strong>／{profile?.summary.totalBadges??74}<small>已取得襟章</small></span><span><strong>{profile?.summary.completedStages??0}</strong>／51<small>已完成關卡</small></span><span><strong>{profile?.summary.firstTryCorrect??0}</strong><small>累積首次答對</small></span></div></div>
 <div className="section-heading"><div><span className="eyebrow">選擇課題世界</span><h2>繼續你的數學冒險</h2></div></div><div className="game-grid"><GameCard title="有向數方塊世界" text="數線、大小、四則運算，共 7 個關卡。" icon={<BookOpen/>} progress={profile?.worldProgress.find(w=>w.worldId==='directed-number')?.completed??0} total={7} href={gameUrl(directedUrl,identity)}/><GameCard title="代數方塊世界" text="代數語言、化簡、代入與數列，共 7 個關卡。" icon={<Calculator/>} progress={profile?.worldProgress.find(w=>w.worldId==='algebra')?.completed??0} total={7} href={gameUrl(algebraUrl,identity)}/><GameCard title="方程方塊世界" text="解方程、建立方程與生活應用，共 6 個關卡。" icon={<Equal/>} progress={profile?.worldProgress.find(w=>w.worldId==='linear-equation')?.completed??0} total={6} href={gameUrl(equationUrl,identity)}/><GameCard title="多項式方塊世界" text="指數律、多項式概念、加減與乘法，共 6 個關卡。" icon={<Braces/>} progress={profile?.worldProgress.find(w=>w.worldId==='polynomial')?.completed??0} total={6} href={gameUrl(polynomialUrl,identity)}/><GameCard title="數值估算方塊世界" text="位值、近似值、有效數字與生活估算，共 5 個關卡。" icon={<Calculator/>} progress={profile?.worldProgress.find(w=>w.worldId==='numerical-estimation')?.completed??0} total={5} href={gameUrl(numericalEstimationUrl,identity)}/><GameCard title="坐標方塊世界" text="坐標、距離、面積與變換，共 9 個關卡。" icon={<Calculator/>} progress={profile?.worldProgress.find(w=>w.worldId==='coordinate')?.completed??0} total={9} href={gameUrl(coordinateUrl,identity)}/><GameCard title="百分法方塊世界" text="百分數、百分變化、盈利與虧蝕及折扣，共 6 個關卡。" icon={<Percent/>} progress={profile?.worldProgress.find(w=>w.worldId==='percentage')?.completed??0} total={6} href={gameUrl(percentageUrl,identity)}/><GameCard title="恆等式方塊世界" text="探索峽谷，練習恆等式、平方差與完全平方，共 5 個關卡。" icon={<Equal/>} progress={profile?.worldProgress.find(w=>w.worldId==='identity')?.completed??0} total={5} href={gameUrl(identityUrl,identity)}/></div>
 <div className="section-heading album-heading"><div><span className="eyebrow">襟章收藏冊</span><h2>本學年收藏</h2></div><button className="refresh" onClick={refresh}><RefreshCcw/>更新收藏</button></div><div className="filters">{filters.map(([id,label])=><button key={id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{label}</button>)}</div>{message&&<p className="notice error">{message}</p>}{loading?<p className="notice">正在更新收藏……</p>:profile?<div className="badge-grid">{badges.map(b=><BadgeCard key={b.id} badge={b}/>)}</div>:<div className="offline"><Shield/><h3>收藏系統尚未連接</h3><p>連接共用 Apps Script 後，這裡會顯示實時襟章及進度。</p></div>}
 </section></main>;
}
function GameCard({title,text,icon,progress,total,href}:{title:string;text:string;icon:React.ReactNode;progress:number;total:number;href:string}){return <a className="game-card" href={href}><span className="game-icon">{icon}</span><span className="card-label">{total} 個關卡</span><h3>{title}</h3><p>{text}</p><div className="progress"><i style={{width:`${progress/total*100}%`}}/></div><span className="card-bottom">已完成 {progress}／{total} <b>進入遊戲 <ChevronRight/></b></span></a>}
// oxlint-disable-next-line next/no-img-element -- Badge PNGs must keep nearest-neighbour pixel rendering.
function BadgeCard({badge}:{badge:Badge}){const hidden=badge.hidden&&!badge.earned;return <article className={`badge-card ${badge.earned?'earned':'locked'} ${hidden?'secret':''}`}><div className="badge-image">{hidden?<Shield/>:<img src={`/badges/${badge.asset}-128.png`} alt=""/>}</div><div><span>{badge.earned&&badge.earnedAt?new Date(badge.earnedAt).toLocaleDateString('zh-HK'):'尚未取得'}</span><h3>{badge.name}</h3><p>{hidden?'隱藏襟章':badge.description}</p>{badge.progress!==null&&badge.target!==null&&!badge.earned&&<div className="badge-progress"><i style={{width:`${badge.progress/badge.target*100}%`}}/><small>{badge.progress}／{badge.target}</small></div>}</div></article>}
