import{equivalent,followsForm,normalizeDisplay,parseExpression,type FormRule,type Variable,variables}from'./algebra.ts';
export type GameId='indices'|'identify'|'order'|'evaluate'|'like-terms'|'add-subtract'|'multiply';
export const gameIds:GameId[]=['indices','identify','order','evaluate','like-terms','add-subtract','multiply'];
export type Choice={value:string;label:string};
export type AlgebraQuestion={kind:'algebra';level:number;variant:number;prompt:string;expression?:string;instruction:string;expected:string;choices?:Choice[];direct:boolean;usedVariables:Variable[];form?:FormRule};
export type NumericQuestion={kind:'numeric';level:number;variant:number;prompt:string;expression:string;instruction:string;answer:number};
export type Question=AlgebraQuestion|NumericQuestion;
export type Session={game:GameId;questions:Question[];index:number;stage:number;errors:number;stageErrors:number;firstTry:number;questionErrors:number;skipped:number;currentFirstTryStreak:number;longestFirstTryStreak:number;solved:boolean;finished:boolean;feedback:string;startedAt:number;completedAt:number|null};
const pick=<T,>(xs:T[])=>xs[Math.floor(Math.random()*xs.length)],rand=(a:number,b:number)=>Math.floor(Math.random()*(b-a+1))+a,nz=(a:number,b:number)=>{let n=0;while(!n)n=rand(a,b);return n},shuffle=<T,>(xs:T[])=>{const out=[...xs];for(let i=out.length-1;i;i--){const j=rand(0,i);[out[i],out[j]]=[out[j],out[i]]}return out},signed=(n:number)=>n<0?`−${Math.abs(n)}`:String(n),pow=(v:string,n:number)=>n===1?v:`${v}^${n}`,term=(c:number,v:string,n=1)=>`${c<0?'−':''}${Math.abs(c)===1?'':Math.abs(c)}${pow(v,n)}`;
function poly(items:[number,string,number][],constant=0){const parts=[...items.filter(([c])=>c).map(([c,v,n])=>({c,text:term(c,v,n)})),...(constant?[{c:constant,text:String(Math.abs(constant))}]:[])];return parts.map((p,i)=>`${i?(p.c<0?' − ':' ＋ '):(p.c<0?'−':'')}${p.text.replace(/^−/,'')}`).join('')||'0'}
function options(answer:string,wrong:string[],labels?:string[]){const values=[answer,...wrong.filter(x=>x!==answer).slice(0,3)];return shuffle(values.map((value,i)=>({value,label:labels?.[i]??normalizeDisplay(value)})))}
const algebra=(level:number,variant:number,prompt:string,expression:string|undefined,instruction:string,expected:string,usedVariables:Variable[],wrong:string[]=[],form?:FormRule,custom?:Choice[]):AlgebraQuestion=>({kind:'algebra',level,variant,prompt,expression,instruction,expected,usedVariables,form,direct:level===2&&!custom,choices:level===2&&!custom?undefined:custom??options(expected,wrong)});
function indices(level:number,variant:number):AlgebraQuestion{const x=pick([...variables]),y=pick(variables.filter(v=>v!==x)),m=rand(1,2),n=rand(1,2),p=rand(1,2);let expression='',answer='';if(level===0){if(variant%2){expression=`${pow(x,m+n)} ÷ ${pow(x,n)}`;answer=pow(x,m)}else{expression=`${pow(x,m)} × ${pow(x,n)}`;answer=pow(x,m+n)}}else if(level===1){if(variant%2){expression=`(${pow(x,m+1)})^2`;answer=pow(x,(m+1)*2)}else{expression=`(${x}${y})^${m+1}`;answer=`${pow(x,m+1)}${pow(y,m+1)}`}}else{expression=variant%2?`(${pow(x,m)}${pow(y,p)})^2 × ${pow(x,n)}`:`${pow(x,m+n)}${pow(y,p+2)} ÷ ${pow(x,n)}${pow(y,2)}`;answer=variant%2?`${pow(x,m*2+n)}${pow(y,p*2)}`:`${pow(x,m)}${pow(y,p)}`}return algebra(level,variant,'運用正整數指數律化簡。',expression,level===2?'輸入最簡答案。':'選出最簡答案。',answer,[x,y],[pow(x,Math.max(1,m+n-1)),`${pow(x,m)}${pow(y,n)}`,pow(x,m*n)],{expanded:true})}
function identify(level:number,variant:number):Question{const x=pick([...variables]);if(level===0){const valid=variant%2===0,expression=valid?poly([[rand(1,6),x,rand(1,5)]],nz(-8,8)):variant===1?`3 ÷ ${x} ＋ 2`:`${x}^−2 ＋ 5`,yes={value:'1',label:'是多項式'},no={value:'0',label:'不是多項式'};return algebra(level,variant,'判斷以下代數式。',expression,'選出正確判斷。',valid?'1':'0',[x],[],undefined,shuffle([yes,no]))}if(level===1){const a=rand(2,6),b=nz(-9,9),d=rand(2,6),expression=poly([[a,x,d],[nz(-7,7),x,rand(1,d-1)]],b),ask=variant%3;return{kind:'numeric',level,variant,prompt:ask===0?'寫出多項式的次數。':ask===1?`寫出 ${pow(x,d)} 項的係數。`:'寫出常數項。',expression,instruction:'使用數字鍵盤輸入答案。',answer:ask===0?d:ask===1?a:b}}const n=rand(2,6),mode=variant%2,expression=mode?`3${pow(x,n)} − 2x ＋ 5`:`4${pow(x,n)} ＋ 2${pow(x,n-1)} − 7`;return{kind:'numeric',level,variant,prompt:mode?'此多項式的次數為多少？':'最高次數為題目所示，求 n。',expression,instruction:mode?'輸入多項式的次數。':'輸入 n 的值。',answer:n}}
function order(level:number,variant:number):AlgebraQuestion{const x=pick([...variables]),degrees=shuffle([1,2,3,4].slice(0,level===0?3:4)),items=degrees.map(d=>[nz(-6,6),x,d]as[number,string,number]),ascending=variant%2===0;if(level===0){const shown=poly([...items].sort((a,b)=>ascending?a[2]-b[2]:b[2]-a[2]));return algebra(level,variant,'判斷排列方式。',shown,'選出正確答案。',ascending?'1':'2',[x],[],undefined,[{value:'1',label:'按升冪排列'},{value:'2',label:'按降冪排列'}])}const constant=nz(-8,8),sorted=[...items].sort((a,b)=>ascending?a[2]-b[2]:b[2]-a[2]),answer=ascending?`${signed(constant)} ＋ ${poly(sorted)}`:poly(sorted,constant),source=poly(shuffle(items),constant),wrong=ascending?poly([...items].sort((a,b)=>b[2]-a[2]),constant):`${signed(constant)} ＋ ${poly([...items].sort((a,b)=>a[2]-b[2]))}`;return algebra(level,variant,`把以下多項式按 ${x} 的${ascending?'升':'降'}冪排列。`,source,level===2?'輸入排列後的多項式。':'選出正確排列。',answer,[x],[wrong,source,`−(${answer})`],{expanded:true,order:ascending?'ascending':'descending'})}
function evaluate(level:number,variant:number):NumericQuestion{while(true){const x=level===0?rand(1,5):nz(-5,5),y=nz(-5,5),a=nz(-6,6),b=nz(-6,6),c=nz(-12,12),expression=level===0?poly([[a,'x',2]],c):level===1?poly([[a,'x',2],[b,'y',1]],c):`${rand(2,4)}(${poly([[a,'x',1],[b,'y',1]],c)})`,factor=level===2?Number(expression.split('(')[0]):1,answer=factor*(a*x+(level===0?0:b*y)+c);if(answer>=-100&&answer<=100)return{kind:'numeric',level,variant,prompt:level===0?`當 x = ${x}`:`當 x = ${signed(x)}，y = ${signed(y)}`,expression,instruction:'求多項式的值。',answer}}}
function likeTerms(level:number,variant:number):Question{const x=pick([...variables]),y=pick(variables.filter(v=>v!==x)),m=rand(2,5),n=rand(1,4);if(level===0){const same=variant%2===0,left=term(rand(2,7),x,m),right=same?term(-rand(2,7),x,m):term(rand(2,7),same?x:y,n);return algebra(level,variant,'判斷兩項是否同類項。',`${left}　和　${right}`,'選出正確判斷。',same?'1':'0',[x,y],[],undefined,[{value:'1',label:'同類項'},{value:'0',label:'異類項'}])}if(level===1){const a=nz(-8,8),b=nz(-8,8),answer=poly([[a+b,x,m]]);return algebra(level,variant,'合併同類項。',`${term(a,x,m)} ＋ ${term(b,x,m)}`,'選出最簡答案。',answer,[x],[term(a-b,x,m),String(a+b),term(a+b,y,m)],{expanded:true})}return{kind:'numeric',level,variant,prompt:'若以下兩項為同類項，求 n。',expression:`${term(3,x,m)}${pow(y,n)}　和　−5${pow(x,m)}${pow(y,variant%3+1)}`,instruction:'輸入 n 的值。',answer:variant%3+1}}
function addSubtract(level:number,variant:number):AlgebraQuestion{const x=pick([...variables]),y=pick(variables.filter(v=>v!==x)),a=nz(-8,8),b=nz(-8,8),c=nz(-8,8),d=nz(-8,8);let expression='',answer='';if(level===0){expression=poly([[a,x,2],[b,x,1],[c,x,2]],d);answer=poly([[a+c,x,2],[b,x,1]],d)}else if(level===1){expression=`(${poly([[a,x,2],[b,x,1]],c)}) − (${poly([[d,x,2],[nz(-6,6),x,1]],nz(-8,8))})`;const parsed=parseExpression(expression);answer=parsed.ok?canonical(parsed.value):'0'}else{expression=`(${poly([[a,x,2],[b,y,1]],c)}) ＋ (${poly([[d,x,2],[nz(-6,6),y,1]],nz(-8,8))}) − (${poly([[nz(-5,5),x,2],[nz(-5,5),y,1]],nz(-8,8))})`;const parsed=parseExpression(expression);answer=parsed.ok?canonical(parsed.value):'0'}return algebra(level,variant,'化簡以下多項式。',expression,level===2?'輸入最簡答案。':'選出最簡答案。',answer,[x,y],[`−(${answer})`,poly([[a-c,x,2],[b,x,1]],d),String(a+b+c+d)],{expanded:true})}
function canonical(value:Map<string,number>){const items=[...value].map(([key,c])=>{const powers=key.split(',').map(Number),v=variables.map((name,i)=>powers[i]?pow(name,powers[i]):'').join('');return{c,v,degree:powers.reduce((a,b)=>a+b,0)}}).sort((a,b)=>b.degree-a.degree);return items.map((item,i)=>`${i?(item.c<0?' − ':' ＋ '):(item.c<0?'−':'')}${Math.abs(item.c)===1&&item.v?'':Math.abs(item.c)}${item.v}`).join('')||'0'}
function multiplyGame(level:number,variant:number):AlgebraQuestion{const x=pick([...variables]),y=pick(variables.filter(v=>v!==x)),a=nz(-5,5),b=nz(-5,5),c=nz(-5,5),d=nz(-5,5);let expression='';if(level===0)expression=`${term(a,x,1)}(${poly([[b,x,1]],c)})`;else if(level===1)expression=`(${poly([[a,x,1]],b)})(${poly([[c,x,1]],d)})`;else expression=variant%2?`(${poly([[a,x,1],[b,y,1]],c)})(${poly([[d,x,1]],nz(-4,4))})`:`${term(a,x,1)}(${poly([[b,x,2],[c,y,1]],d)}) ＋ ${poly([[nz(-5,5),x,2]],nz(-8,8))}`;const parsed=parseExpression(expression),answer=parsed.ok?canonical(parsed.value):'0';return algebra(level,variant,'展開並化簡。',expression,level===2?'輸入最簡答案。':'選出最簡答案。',answer,[x,y],[`−(${answer})`,String(a*b),poly([[a+b,x,2]],c+d)],{expanded:true})}
function generate(game:GameId,level:number,variant:number):Question{if(game==='indices')return indices(level,variant);if(game==='identify')return identify(level,variant);if(game==='order')return order(level,variant);if(game==='evaluate')return evaluate(level,variant);if(game==='like-terms')return likeTerms(level,variant);if(game==='add-subtract')return addSubtract(level,variant);return multiplyGame(level,variant)}
export const questionKey=(q:Question)=>q.kind==='numeric'?`${q.prompt}|${q.expression}|${q.answer}`:`${q.prompt}|${q.expression}|${q.expected}`;
export function makeQuestions(game:GameId,previous:Question[]=[]){const used=new Set(previous.map(questionKey)),out:Question[]=[];for(let level=0;level<3;level++){let attempts=0;while(out.length<(level+1)*5){if(++attempts>5000)throw new Error('未能產生足夠的不重複題目。');const variant=out.length-level*5,q=generate(game,level,variant),k=questionKey(q);if(!used.has(k)&&!out.some(x=>questionKey(x)===k)){out.push(q);used.add(k)}}}return[...shuffle(out.slice(0,5)),...shuffle(out.slice(5,10)),...shuffle(out.slice(10,15))]}
export function startSession(game:GameId,questions=makeQuestions(game),now=Date.now()):Session{return{game,questions,index:0,stage:0,errors:0,stageErrors:0,firstTry:0,questionErrors:0,skipped:0,currentFirstTryStreak:0,longestFirstTryStreak:0,solved:false,finished:false,feedback:'',startedAt:now,completedAt:null}}
export function expected(s:Session){const q=s.questions[s.index];return q.kind==='numeric'?String(q.answer):q.expected}
function correct(s:Session,now:number){const finished=s.index===s.questions.length-1,first=s.questionErrors===0,streak=first?s.currentFirstTryStreak+1:0;return{...s,solved:true,finished,completedAt:finished?now:null,firstTry:s.firstTry+(first?1:0),currentFirstTryStreak:streak,longestFirstTryStreak:Math.max(s.longestFirstTryStreak,streak),feedback:`答對了！這題獲得 ${first?10:5} 分。`}}
const hints:Record<GameId,string>={indices:'留意相乘、相除及冪的指數律。',identify:'檢查每個變數的指數是否為正整數。',order:'先比較每一項的次數。',evaluate:'先代入字母的值，再按運算次序計算。','like-terms':'同類項的變數及各指數必須完全相同。','add-subtract':'只有同類項才可合併，減括號要改變每項符號。',multiply:'括號內每一項都要相乘，再合併同類項。'};
export function submit(s:Session,answer:string,now=Date.now()):Session{if(s.finished||s.solved)return s;const q=s.questions[s.index];if(q.kind==='numeric'){if(answer.trim()==='')return{...s,feedback:'請輸入答案。'};if(answer===String(q.answer))return correct(s,now)}else{const parsed=parseExpression(answer);if(!parsed.ok)return{...s,feedback:parsed.message};if(equivalent(answer,q.expected)){if(!followsForm(answer,q.form))return{...s,feedback:'答案等值，但未符合指定的排列或展開形式。'};return correct(s,now)}}return{...s,errors:s.errors+1,questionErrors:s.questionErrors+1,stageErrors:s.stageErrors+1,currentFirstTryStreak:0,feedback:`再試一次。${hints[s.game]}`}}
export function skipQuestion(s:Session,now=Date.now()):Session{if(s.finished||s.solved||s.index<10)return s;const finished=s.index===s.questions.length-1;return{...s,skipped:s.skipped+1,solved:true,finished,completedAt:finished?now:null,currentFirstTryStreak:0,feedback:'已放棄本題，這題不計分。'}}
export const score=(s:Session)=>{const completed=s.index+(s.solved?1:0);return s.firstTry*10+Math.max(0,completed-s.firstTry-s.skipped)*5},elapsedSeconds=(s:Session,now:number)=>Math.max(0,Math.floor(((s.completedAt??now)-s.startedAt)/1000));
export function nextQuestion(s:Session):Session{return!s.solved||s.finished?s:{...s,index:s.index+1,stage:0,stageErrors:0,questionErrors:0,solved:false,feedback:''}}
export type Action={type:'start';session:Session}|{type:'answer';value:string}|{type:'next'}|{type:'skip'}|{type:'home'};
export function reducer(s:Session|null,a:Action):Session|null{if(a.type==='home')return null;if(a.type==='start')return a.session;if(!s)return s;if(a.type==='answer')return submit(s,a.value);if(a.type==='skip')return skipQuestion(s);return nextQuestion(s)}
