import{equivalent,followsForm,normalizeDisplay,parseExpression,type FormRule,type Variable,variables}from'./algebra.ts';
export type GameId='indices'|'identify'|'order'|'like-terms'|'add-subtract'|'multiply';
export const GAME_TIME_LIMIT_SECONDS=60*60;
export const gameIds:GameId[]=['indices','identify','order','like-terms','add-subtract','multiply'];
export type Choice={value:string;label:string};
export type AlgebraQuestion={kind:'algebra';level:number;variant:number;prompt:string;expression?:string;instruction:string;expected:string;choices?:Choice[];direct:boolean;usedVariables:Variable[];form?:FormRule};
export type NumericQuestion={kind:'numeric';level:number;variant:number;prompt:string;expression:string;instruction:string;answer:number};
export type Question=AlgebraQuestion|NumericQuestion;
export type Session={game:GameId;questions:Question[];index:number;stage:number;errors:number;stageErrors:number;firstTry:number;questionErrors:number;skipped:number;currentFirstTryStreak:number;longestFirstTryStreak:number;solved:boolean;finished:boolean;expired:boolean;feedback:string;startedAt:number;completedAt:number|null};
const pick=<T,>(xs:T[])=>xs[Math.floor(Math.random()*xs.length)],rand=(a:number,b:number)=>Math.floor(Math.random()*(b-a+1))+a,nz=(a:number,b:number)=>{let n=0;while(!n)n=rand(a,b);return n},shuffle=<T,>(xs:T[])=>{const out=[...xs];for(let i=out.length-1;i;i--){const j=rand(0,i);[out[i],out[j]]=[out[j],out[i]]}return out},signed=(n:number)=>n<0?`−${Math.abs(n)}`:String(n),pow=(v:string,n:number)=>n===1?v:`${v}^${n}`,term=(c:number,v:string,n=1)=>c===0?'0':`${c<0?'−':''}${Math.abs(c)===1?'':Math.abs(c)}${pow(v,n)}`;
const twoVariableTerm=(coefficient:number,first:Variable,firstPower:number,second:Variable,secondPower:number)=>coefficient===0?'0':`${term(coefficient,first,firstPower)}${pow(second,secondPower)}`;
function poly(items:[number,string,number][],constant=0){const parts=[...items.filter(([c])=>c).map(([c,v,n])=>({c,text:term(c,v,n)})),...(constant?[{c:constant,text:String(Math.abs(constant))}]:[])];return parts.map((p,i)=>`${i?(p.c<0?' − ':' ＋ '):(p.c<0?'−':'')}${p.text.replace(/^−/,'')}`).join('')||'0'}
function constantFirst(constant:number,rest:string){return`${signed(constant)}${rest.startsWith('−')?` − ${rest.slice(1)}`:` ＋ ${rest}`}`}
function joinSum(left:string,right:string){return`${left}${right.startsWith('−')?` − ${right.slice(1)}`:` ＋ ${right}`}`}
function powerDistractors(variable:string,answerExponent:number,candidates:number[]){const exponents:number[]=[];for(const exponent of[...candidates,1,2,3,4,5,6])if(exponent>=1&&exponent<=6&&exponent!==answerExponent&&!exponents.includes(exponent))exponents.push(exponent);return exponents.slice(0,3).map(exponent=>pow(variable,exponent))}
function gcd(a:number,b:number){a=Math.abs(a);b=Math.abs(b);while(b)[a,b]=[b,a%b];return a||1}
function coprimePair(){let numerator=rand(1,5),denominator=rand(1,5);while(gcd(numerator,denominator)!==1||numerator===denominator){numerator=rand(1,5);denominator=rand(1,5)}return[numerator,denominator]as const}
function rationalMonomial(numerator:number,denominator:number,powers:Partial<Record<Variable,number>>){
 if(denominator<0){numerator=-numerator;denominator=-denominator}
 const divisor=gcd(numerator,denominator);numerator/=divisor;denominator/=divisor;
 const numeratorVariables=variables.filter(variable=>(powers[variable]||0)>0).map(variable=>pow(variable,powers[variable]||0)).join('');
 const denominatorVariables=variables.filter(variable=>(powers[variable]||0)<0).map(variable=>pow(variable,-(powers[variable]||0))).join('');
 const numeratorText=`${numerator<0?'−':''}${Math.abs(numerator)===1&&numeratorVariables?'':Math.abs(numerator)}${numeratorVariables}`;
 const denominatorText=`${denominator===1&&denominatorVariables?'':denominator}${denominatorVariables}`;
 if(denominatorText==='1'||!denominatorText)return numeratorText;
 return`${numeratorText} ÷ ${denominator!==1&&denominatorVariables?`(${denominatorText})`:denominatorText}`;
}
function nearbyDistractors(answer:string){const parsed=parseExpression(answer);if(!parsed.ok)return[];const entries=[...parsed.value.entries()];if(!entries.length)return['1','−1','2'];const changed=(index:number,coefficient:number)=>{const value=new Map(parsed.value);if(coefficient)value.set(entries[index][0],coefficient);else value.delete(entries[index][0]);return canonical(value)};const first=entries[0][1],last=entries.length-1;return[
 changed(0,first+(first>0?1:-1)),
 changed(last,-entries[last][1]),
 entries.length>1?changed(last,0):changed(0,first+(first>0?-1:1)),
 canonical(new Map(entries.map(([key,value])=>[key,-value]))),
 ];}
function options(answer:string,wrong:string[]){const values:string[]=[],labels=new Set<string>();for(const value of[answer,...wrong,...nearbyDistractors(answer)]){const label=normalizeDisplay(value);if(!values.includes(value)&&!labels.has(label)){values.push(value);labels.add(label)}}if(values.length<4)throw new Error(`未能為「${answer}」建立四個獨立選項。`);return shuffle(values.slice(0,4).map(value=>({value,label:normalizeDisplay(value)})))}
const algebra=(level:number,variant:number,prompt:string,expression:string|undefined,instruction:string,expected:string,usedVariables:Variable[],wrong:string[]=[],form?:FormRule,custom?:Choice[]):AlgebraQuestion=>({kind:'algebra',level,variant,prompt,expression,instruction,expected,usedVariables,form,direct:level===2&&!custom,choices:level===2&&!custom?undefined:custom??options(expected,wrong)});
function indices(level:number,variant:number):AlgebraQuestion{
 const x=pick([...variables]);
 let expression='',answer='',wrong:string[]=[],usedVariables:Variable[]=[x];
 if(level===0){
  const m=rand(1,2),n=rand(1,2);
  if(variant%2){const exponent=m;expression=`${pow(x,m+n)} ÷ ${pow(x,n)}`;answer=pow(x,exponent);wrong=powerDistractors(x,exponent,[m+n,n,Math.abs(m+n-n)+1])}
  else{const exponent=m+n;expression=`${pow(x,m)} × ${pow(x,n)}`;answer=pow(x,exponent);wrong=powerDistractors(x,exponent,[m*n,Math.max(m,n),Math.abs(m-n)||1])}
 }else if(level===1){
  const[reducedNumerator,reducedDenominator]=coprimePair(),factor=rand(2,6),signPatterns=[[-1,1],[1,1],[-1,-1],[1,-1],[-1,1]],signs=signPatterns[variant],numeratorCoefficient=signs[0]*reducedNumerator*factor,denominatorCoefficient=signs[1]*reducedDenominator*factor;
  const denominatorLarger=variant<3,smallerExponent=rand(2,6),difference=rand(2,9),numeratorExponent=denominatorLarger?smallerExponent:smallerExponent+difference,denominatorExponent=denominatorLarger?smallerExponent+difference:smallerExponent,answerExponent=numeratorExponent-denominatorExponent;
  expression=`${term(numeratorCoefficient,x,numeratorExponent)} ÷ (${term(denominatorCoefficient,x,denominatorExponent)})`;
  answer=rationalMonomial(numeratorCoefficient,denominatorCoefficient,{[x]:answerExponent});
  wrong=[
   rationalMonomial(numeratorCoefficient,denominatorCoefficient,{[x]:-answerExponent}),
   rationalMonomial(-numeratorCoefficient,denominatorCoefficient,{[x]:answerExponent}),
   rationalMonomial(numeratorCoefficient,denominatorCoefficient,{[x]:Math.min(20,numeratorExponent+denominatorExponent)}),
  ];
 }else{
  if(variant===0){
   const coefficient=rand(2,4)*(Math.random()<.5?-1:1),p=rand(2,4),q=rand(1,2),r=2,answerExponent=p+q*r;
   expression=`${term(coefficient,x,p)} × (${pow(x,q)})^${r}`;
   answer=rationalMonomial(coefficient,1,{[x]:answerExponent});
  }else if(variant===1){
   const[reducedNumerator,reducedDenominator]=coprimePair(),factor=rand(2,5),numeratorCoefficient=reducedNumerator*factor*(Math.random()<.5?-1:1),denominatorCoefficient=reducedDenominator*factor,q=rand(2,3),r=rand(3,4),poweredExponent=q*r,difference=rand(1,Math.min(9,poweredExponent-1)),numeratorExponent=poweredExponent-difference;
   expression=`${term(numeratorCoefficient,x,numeratorExponent)} ÷ (${denominatorCoefficient}(${pow(x,q)})^${r})`;
   answer=rationalMonomial(numeratorCoefficient,denominatorCoefficient,{[x]:-difference});
  }else if(variant===2){
   const[reducedNumerator,reducedDenominator]=coprimePair(),factor=rand(2,5),numeratorCoefficient=reducedNumerator*factor*(Math.random()<.5?-1:1),denominatorCoefficient=reducedDenominator*factor,p=rand(4,6),q=2,poweredExponent=p*q,difference=rand(1,Math.min(8,poweredExponent-1)),denominatorExponent=poweredExponent-difference;
   expression=`${signed(numeratorCoefficient)}(${pow(x,p)})^${q} ÷ (${term(denominatorCoefficient,x,denominatorExponent)})`;
   answer=rationalMonomial(numeratorCoefficient,denominatorCoefficient,{[x]:difference});
  }else if(variant===3){
   const y=pick(variables.filter(variable=>variable!==x)),coefficient=rand(2,3)*(Math.random()<.5?-1:1),p=rand(1,2),q=rand(1,2),r=rand(2,3),xDifference=rand(1,5),denominatorExponent=p*r+xDifference;
   usedVariables=[x,y];
   expression=`(${term(coefficient,x,p)}${pow(y,q)})^${r} ÷ ${pow(x,denominatorExponent)}`;
   answer=rationalMonomial(coefficient**r,1,{[x]:-xDifference,[y]:q*r});
  }else{
   const coefficient=2,numeratorFactor=rand(2,4),denominatorCoefficient=rand(3,8),p=rand(1,2),q=rand(2,3),extraExponent=rand(1,2),combinedExponent=p*q+extraExponent,difference=rand(1,Math.min(9,20-combinedExponent)),denominatorExponent=combinedExponent+difference;
   expression=`(${term(-coefficient,x,p)})^${q} × ${term(numeratorFactor,x,extraExponent)} ÷ (${term(denominatorCoefficient,x,denominatorExponent)})`;
   answer=rationalMonomial((-coefficient)**q*numeratorFactor,denominatorCoefficient,{[x]:-difference});
  }
 }
 return algebra(level,variant,'運用正整數指數律化簡。',expression,level===2?'輸入最簡答案。':'選出最簡答案。',answer,usedVariables,wrong);
}
function identify(level:number,variant:number):Question{const x=pick([...variables]);if(level===0){const valid=variant%2===0,expression=valid?poly([[rand(1,6),x,rand(1,5)]],nz(-8,8)):variant===1?`3 ÷ ${x} ＋ 2`:`${x}^−2 ＋ 5`,yes={value:'1',label:'是多項式'},no={value:'0',label:'不是多項式'};return algebra(level,variant,'判斷以下代數式。',expression,'選出正確判斷。',valid?'1':'0',[x],[],undefined,shuffle([yes,no]))}if(level===1){const a=rand(2,6),b=nz(-9,9),d=rand(2,6),expression=poly([[a,x,d],[nz(-7,7),x,rand(1,d-1)]],b),ask=variant%3;return{kind:'numeric',level,variant,prompt:ask===0?'寫出多項式的次數。':ask===1?`寫出 ${pow(x,d)} 項的係數。`:'寫出常數項。',expression,instruction:'使用數字鍵盤輸入答案。',answer:ask===0?d:ask===1?a:b}}const mode=variant%3;if(mode===0){const degree=rand(3,6);return{kind:'numeric',level,variant,prompt:`若 n 為正整數，且多項式的次數為 ${degree}，求 n。`,expression:`3${x}ⁿ − 2${pow(x,2)} ＋ 5`,instruction:'輸入 n 的值。',answer:degree}}if(mode===1){const degree=rand(3,6);return{kind:'numeric',level,variant,prompt:`若 n 為正整數，且多項式的次數為 ${degree}，求 n。`,expression:`4${x}ⁿ⁺¹ ＋ 2${pow(x,2)} − 7`,instruction:'輸入 n 的值。',answer:degree-1}}const n=rand(2,3);return{kind:'numeric',level,variant,prompt:`若 n 為正整數，且多項式的次數為 ${2*n}，求 n。`,expression:`5${x}²ⁿ ＋ 3${x} − 4`,instruction:'輸入 n 的值。',answer:n}}
function order(level:number,variant:number):AlgebraQuestion{const x=pick([...variables]),gapPatterns=[[[1,2,4],[1,3,4],[1,2,5],[2,4,5],[1,3,5]],[[1,2,4,6],[1,3,5,6],[2,3,5,6],[1,4,5,6],[2,4,5,6]]]as const,degrees=shuffle(level===0?[1,2,3]:[...gapPatterns[level-1][variant]]),items=degrees.map(d=>[nz(-6,6),x,d]as[number,string,number]),ascending=variant%2===0;if(level===0){const shown=poly([...items].sort((a,b)=>ascending?a[2]-b[2]:b[2]-a[2]));return algebra(level,variant,'判斷排列方式。',shown,'選出正確答案。',ascending?'1':'2',[x],[],undefined,[{value:'1',label:'按升冪排列'},{value:'2',label:'按降冪排列'}])}const constant=nz(-8,8),sorted=[...items].sort((a,b)=>ascending?a[2]-b[2]:b[2]-a[2]),answer=ascending?constantFirst(constant,poly(sorted)):poly(sorted,constant),sourceItems=[...sorted.slice(1),sorted[0]],source=poly(sourceItems,constant),opposite=[...items].sort((a,b)=>ascending?b[2]-a[2]:a[2]-b[2]),wrong=ascending?poly(opposite,constant):constantFirst(constant,poly(opposite)),swapped=[...sorted];[swapped[1],swapped[2]]=[swapped[2],swapped[1]];const mixed=ascending?constantFirst(constant,poly(swapped)):poly(swapped,constant);return algebra(level,variant,`把以下缺項多項式按 ${x} 的${ascending?'升':'降'}冪排列。`,source,level===2?'輸入排列後的多項式。':'選出正確排列。',answer,[x],[wrong,source,mixed],{expanded:true,order:ascending?'ascending':'descending'})}
function likeTerms(level:number,variant:number):Question{const x=pick([...variables]),y=pick(variables.filter(v=>v!==x)),m=variant===0?1:rand(2,5);let n=variant===0?1:rand(1,5);while(variant!==0&&n===m)n=rand(1,5);if(level===0){const same=variant%2===0,left=twoVariableTerm(rand(2,7),x,m,y,n),right=same?twoVariableTerm(-rand(2,7),y,n,x,m):twoVariableTerm(-rand(2,7),y,m,x,n);return algebra(level,variant,'判斷兩項是否同類項。',`${left}　和　${right}`,'留意字母次序，再選出正確判斷。',same?'1':'0',[x,y],[],undefined,shuffle([{value:'1',label:'同類項'},{value:'0',label:'異類項'}]))}if(level===1){const a=nz(-8,8);let b=nz(-8,8);while(a+b===0)b=nz(-8,8);const expression=joinSum(twoVariableTerm(a,x,m,y,n),twoVariableTerm(b,y,n,x,m)),answer=twoVariableTerm(a+b,x,m,y,n);return algebra(level,variant,'合併次序不同的同類項。',expression,'選出最簡答案。',answer,[x,y],[twoVariableTerm(a-b,x,m,y,n),twoVariableTerm(a+b,x,n,y,m),twoVariableTerm(a+b+Math.sign(a+b),x,m,y,n)],{expanded:true})}const answer=variant%3+1,fixedPower=rand(2,5),swap=variant%2===1;return{kind:'numeric',level,variant,prompt:'若以下兩項為同類項，求 n。',expression:swap?`3${pow(y,fixedPower)}${x}ⁿ　和　−5${pow(x,answer)}${pow(y,fixedPower)}`:`3${x}ⁿ${pow(y,fixedPower)}　和　−5${pow(y,fixedPower)}${pow(x,answer)}`,instruction:'字母次序不影響同類項，輸入 n 的值。',answer}}
function addSubtract(level:number,variant:number):AlgebraQuestion{const x=pick([...variables]),y=pick(variables.filter(v=>v!==x)),a=nz(-8,8),b=nz(-8,8),c=nz(-8,8),d=nz(-8,8);let expression='',answer='',wrong:string[]=[];if(level===0){expression=poly([[a,x,2],[b,x,1],[c,x,2]],d);answer=poly([[a+c,x,2],[b,x,1]],d);wrong=[poly([[a-c,x,2],[b,x,1]],d),poly([[a+c+b,x,2]],d),poly([[a,x,2],[b,x,1]],d)]}else if(level===1){const e=nz(-6,6),f=nz(-8,8),operator=variant%2===0?'＋':'−';expression=`(${poly([[a,x,2],[b,x,1]],c)}) ${operator} (${poly([[d,x,2],[e,x,1]],f)})`;const parsed=parseExpression(expression);answer=parsed.ok?canonical(parsed.value):'0'}else{const polynomials=[poly([[a,x,2],[b,y,1]],c),poly([[d,x,2],[nz(-6,6),y,1]],nz(-8,8)),poly([[nz(-5,5),x,2],[nz(-5,5),y,1]],nz(-8,8))],patterns=[[1,1,-1],[1,-1,1],[-1,1,-1],[-1,-1,1],[1,-1,-1]],signs=patterns[variant%patterns.length];expression=`${signs[0]<0?'−':''}(${polynomials[0]}) ${signs[1]<0?'−':'＋'} (${polynomials[1]}) ${signs[2]<0?'−':'＋'} (${polynomials[2]})`;const parsed=parseExpression(expression);answer=parsed.ok?canonical(parsed.value):'0'}return algebra(level,variant,'化簡以下多項式。',expression,level===2?'輸入最簡答案。':'選出最簡答案。',answer,[x,y],wrong,{expanded:true})}
function canonical(value:Map<string,number>){const items=[...value].map(([key,c])=>{const powers=key.split(',').map(Number),v=variables.map((name,i)=>powers[i]?pow(name,powers[i]):'').join('');return{c,v,degree:powers.reduce((a,b)=>a+b,0)}}).sort((a,b)=>b.degree-a.degree);return items.map((item,i)=>`${i?(item.c<0?' − ':' ＋ '):(item.c<0?'−':'')}${Math.abs(item.c)===1&&item.v?'':Math.abs(item.c)}${item.v}`).join('')||'0'}
function multiplyGame(level:number,variant:number):AlgebraQuestion{const x=pick([...variables]),y=pick(variables.filter(v=>v!==x)),a=nz(-5,5),b=nz(-5,5),c=nz(-5,5),d=nz(-5,5);let expression='',wrong:string[]=[];if(level===0){expression=`${term(a,x,1)}(${poly([[b,x,1]],c)})`;wrong=[poly([[a*b,x,2],[c,x,1]]),poly([[a*b,x,2],[-a*c,x,1]]),poly([[a+b,x,2],[a+c,x,1]])]}else if(level===1){expression=`(${poly([[a,x,1]],b)})(${poly([[c,x,1]],d)})`;wrong=[poly([[a*c,x,2],[a*d,x,1]],b*d),poly([[a*c,x,2],[a*d+b*c,x,1]],-b*d),poly([[a+c,x,2],[b+d,x,1]],b*d)]}else expression=variant%2?`(${poly([[a,x,1],[b,y,1]],c)})(${poly([[d,x,1]],nz(-4,4))})`:joinSum(`${term(a,x,1)}(${poly([[b,x,2],[c,y,1]],d)})`,poly([[nz(-5,5),x,2]],nz(-8,8)));const parsed=parseExpression(expression),answer=parsed.ok?canonical(parsed.value):'0';return algebra(level,variant,'展開並化簡。',expression,level===2?'輸入最簡答案。':'選出最簡答案。',answer,[x,y],wrong,{expanded:true})}
function generate(game:GameId,level:number,variant:number):Question{if(game==='indices')return indices(level,variant);if(game==='identify')return identify(level,variant);if(game==='order')return order(level,variant);if(game==='like-terms')return likeTerms(level,variant);if(game==='add-subtract')return addSubtract(level,variant);return multiplyGame(level,variant)}
export const questionKey=(q:Question)=>q.kind==='numeric'?`${q.prompt}|${q.expression}|${q.answer}`:`${q.prompt}|${q.expression}|${q.expected}`;
export function makeQuestions(game:GameId,previous:Question[]=[]){const used=new Set(previous.map(questionKey)),out:Question[]=[];for(let level=0;level<3;level++){let attempts=0;while(out.length<(level+1)*5){if(++attempts>5000)throw new Error('未能產生足夠的不重複題目。');const variant=out.length-level*5,q=generate(game,level,variant),k=questionKey(q);if(!used.has(k)&&!out.some(x=>questionKey(x)===k)){out.push(q);used.add(k)}}}return[...shuffle(out.slice(0,5)),...shuffle(out.slice(5,10)),...shuffle(out.slice(10,15))]}
export function startSession(game:GameId,questions=makeQuestions(game),now=Date.now()):Session{return{game,questions,index:0,stage:0,errors:0,stageErrors:0,firstTry:0,questionErrors:0,skipped:0,currentFirstTryStreak:0,longestFirstTryStreak:0,solved:false,finished:false,expired:false,feedback:'',startedAt:now,completedAt:null}}
export function expected(s:Session){const q=s.questions[s.index];return q.kind==='numeric'?String(q.answer):q.expected}
function correct(s:Session,now:number){const finished=s.index===s.questions.length-1,first=s.questionErrors===0,streak=first?s.currentFirstTryStreak+1:0;return{...s,solved:true,finished,completedAt:finished?now:null,firstTry:s.firstTry+(first?1:0),currentFirstTryStreak:streak,longestFirstTryStreak:Math.max(s.longestFirstTryStreak,streak),feedback:`答對了！這題獲得 ${first?10:5} 分。`}}
export function expireSession(s:Session,now=Date.now()):Session{return s.finished?s:{...s,solved:false,finished:true,expired:true,completedAt:now,feedback:'遊戲時間已達 1 小時，本局已結束。'}}
const hints:Record<GameId,string>={indices:'留意相乘、相除及冪的指數律。',identify:'檢查每個變數的指數是否為正整數。',order:'缺少的次方不用補上，按現有各項的次數排列。','like-terms':'字母的先後次序不影響乘積；比較每個字母的指數。','add-subtract':'只有同類項才可合併，減括號要改變每項符號。',multiply:'括號內每一項都要相乘，再合併同類項。'};
export function submit(s:Session,answer:string,now=Date.now()):Session{if(s.finished||s.solved)return s;const q=s.questions[s.index];if(q.kind==='numeric'){if(answer.trim()==='')return{...s,feedback:'請輸入答案。'};if(answer===String(q.answer))return correct(s,now)}else{const parsed=parseExpression(answer);if(!parsed.ok)return{...s,feedback:parsed.message};if(equivalent(answer,q.expected)){if(!followsForm(answer,q.form))return{...s,feedback:'答案等值，但未符合指定的排列或展開形式。'};return correct(s,now)}}return{...s,errors:s.errors+1,questionErrors:s.questionErrors+1,stageErrors:s.stageErrors+1,currentFirstTryStreak:0,feedback:`再試一次。${hints[s.game]}`}}
export function skipQuestion(s:Session,now=Date.now()):Session{if(s.finished||s.solved||s.index<10)return s;const finished=s.index===s.questions.length-1;return{...s,skipped:s.skipped+1,solved:true,finished,completedAt:finished?now:null,currentFirstTryStreak:0,feedback:'已放棄本題，這題不計分。'}}
export const score=(s:Session)=>{const completed=s.index+(s.solved?1:0);return s.firstTry*10+Math.max(0,completed-s.firstTry-s.skipped)*5},elapsedSeconds=(s:Session,now:number)=>Math.max(0,Math.floor(((s.completedAt??now)-s.startedAt)/1000));
export function nextQuestion(s:Session):Session{return!s.solved||s.finished?s:{...s,index:s.index+1,stage:0,stageErrors:0,questionErrors:0,solved:false,feedback:''}}
export type Action={type:'start';session:Session}|{type:'answer';value:string}|{type:'next'}|{type:'skip'}|{type:'timeout'}|{type:'home'};
export function reducer(s:Session|null,a:Action):Session|null{if(a.type==='home')return null;if(a.type==='start')return a.session;if(!s)return s;if(a.type==='answer')return submit(s,a.value);if(a.type==='skip')return skipQuestion(s);if(a.type==='timeout')return expireSession(s);return nextQuestion(s)}
