export type GameId='read-coordinates'|'plot-points'|'quadrants'|'horizontal-vertical'|'distance'|'area'|'translation'|'reflection'|'rotation';
export const GAME_TIME_LIMIT_SECONDS=60*60;
export const gameIds:GameId[]=['read-coordinates','plot-points','quadrants','horizontal-vertical','distance','area','translation','reflection','rotation'];
export type Point={x:number;y:number;label?:string};
export type Segment={a:Point;b:Point};
export type BaseQuestion={level:number;variant:number;prompt:string;instruction:string;points?:Point[];segments?:Segment[];polygon?:Point[];axisLine?:{axis:'x'|'y';value:number};hints:string[]};
export type CoordinateQuestion=BaseQuestion&{kind:'coordinate';answer:Point;input:'text'|'plot'};
export type ChoiceQuestion=BaseQuestion&{kind:'choice';answer:string;choices:string[]};
export type NumericQuestion=BaseQuestion&{kind:'numeric';answer:number;suffix:string};
export type Question=CoordinateQuestion|ChoiceQuestion|NumericQuestion;
export type Session={game:GameId;questions:Question[];index:number;errors:number;stageErrors:number;firstTry:number;questionErrors:number;skipped:number;currentFirstTryStreak:number;longestFirstTryStreak:number;solved:boolean;finished:boolean;expired:boolean;feedback:string;startedAt:number;completedAt:number|null};

const rand=(a:number,b:number)=>Math.floor(Math.random()*(b-a+1))+a;
const pick=<T,>(items:T[])=>items[rand(0,items.length-1)];
const shuffle=<T,>(items:T[])=>{const out=[...items];for(let i=out.length-1;i;i--){const j=rand(0,i);[out[i],out[j]]=[out[j],out[i]]}return out};
const point=(min=-8,max=8,allowZero=true):Point=>{let x=rand(min,max),y=rand(min,max);if(!allowZero){while(x===0)x=rand(min,max);while(y===0)y=rand(min,max)}return{x,y}};
const fmt=({x,y}:Point)=>`(${x}, ${y})`;
const signed=(n:number)=>n<0?`−${Math.abs(n)}`:String(n);
const axisName=(p:Point)=>p.x===0&&p.y===0?'原點':p.x===0?'y 軸':p.y===0?'x 軸':p.x>0&&p.y>0?'象限 I':p.x<0&&p.y>0?'象限 II':p.x<0&&p.y<0?'象限 III':'象限 IV';
const coordinate=(level:number,variant:number,prompt:string,instruction:string,answer:Point,input:'text'|'plot',extra:Partial<BaseQuestion>={}):CoordinateQuestion=>({kind:'coordinate',level,variant,prompt,instruction,answer,input,hints:['先找 x 坐標，再找 y 坐標。','沿 x 軸和 y 軸畫輔助線，再確認正負號。'],...extra});
const choice=(level:number,variant:number,prompt:string,instruction:string,answer:string,choices:string[],extra:Partial<BaseQuestion>={}):ChoiceQuestion=>({kind:'choice',level,variant,prompt,instruction,answer,choices:[...choices],hints:['比較兩個坐標的正負號或相同部分。','在坐標圖上畫水平及鉛垂輔助線。'],...extra});
const numeric=(level:number,variant:number,prompt:string,instruction:string,answer:number,suffix:string,extra:Partial<BaseQuestion>={}):NumericQuestion=>({kind:'numeric',level,variant,prompt,instruction,answer,suffix,hints:['先從坐標找出所需的長度。','寫出中間算式，再計算答案。'],...extra});

function comprehensivePoint(variant:number){if(variant===0)return{x:0,y:0};if(variant===1)return{x:rand(-8,8)||4,y:0};if(variant===2)return{x:0,y:rand(-8,8)||-3};return point(-8,8,false)}
function readCoordinates(level:number,variant:number){const p=level===0?point(1,6,false):level===1?point(-6,6,false):comprehensivePoint(variant),label=pick(['A','B','P','Q','R']);return coordinate(level,variant,`寫出圖中 ${label} 點的坐標。`,'必須輸入括號、逗號及兩個坐標。',p,'text',{points:[{...p,label}]})}
function plotPoints(level:number,variant:number){const p=level===0?point(1,6,false):level===1?point(-6,6,false):comprehensivePoint(variant),label=pick(['A','B','P','Q','R']);return coordinate(level,variant,`在坐標平面上標示 ${label}${fmt(p)}。`,'點選格點，再按「檢查答案」。',p,'plot')}
function quadrants(level:number,variant:number){
 const options=['象限 I','象限 II','象限 III','象限 IV','x 軸','y 軸','原點'];
 if(level===0){const p=point(-8,8,false);return choice(level,variant,'圖中的 A 點在哪一個象限？','選出正確答案。',axisName(p),options.slice(0,4),{points:[{...p,label:'A'}]})}
 if(level===1){const quadrant=pick(options.slice(0,4));let p=point(-8,8,false);while(axisName(p)!==quadrant)p=point(-8,8,false);const others:Point[]=[];while(others.length<3){const candidate=point(-8,8,false);if(axisName(candidate)!==quadrant&&!others.some(item=>item.x===candidate.x&&item.y===candidate.y))others.push(candidate)}const labels=shuffle([p,...others]).map((v,i)=>({...v,label:String.fromCharCode(65+i)})),answer=labels.find(item=>item.x===p.x&&item.y===p.y)?.label||'A';return choice(level,variant,`哪一點位於${quadrant}？`,'根據各點坐標的正負號判斷。',answer,['A','B','C','D'],{points:labels})}
 const p=variant<2?point(-8,8,false):variant===2?{x:0,y:rand(-8,8)||3}:variant===3?{x:rand(-8,8)||-4,y:0}:{x:0,y:0},label=pick(['A','B','P','Q','R']);return choice(level,variant,`點 ${label}${fmt(p)} 位於哪裏？`,'坐標軸上的點不屬於任何象限。',axisName(p),options)
}
function horizontalVertical(level:number,variant:number){
 if(level===0){const horizontal=variant%2===0,a=point(-6,6,true),b=horizontal?{x:rand(-8,8),y:a.y}:{x:a.x,y:rand(-8,8)};return choice(level,variant,'線段 AB 是水平線還是鉛垂線？','觀察哪一個坐標保持不變。',horizontal?'水平線':'鉛垂線',['水平線','鉛垂線'],{points:[{...a,label:'A'},{...b,label:'B'}],segments:[{a,b}]})}
 if(level===1){const mode=variant%3,a=point(-8,8,true);let b=mode===0?{x:rand(-8,8),y:a.y}:mode===1?{x:a.x,y:rand(-8,8)}:point(-8,8,true);while(b.x===a.x&&b.y===a.y||mode===2&&(b.x===a.x||b.y===a.y))b=mode===0?{x:rand(-8,8),y:a.y}:mode===1?{x:a.x,y:rand(-8,8)}:point(-8,8,true);const answer=mode===0?'水平線':mode===1?'鉛垂線':'兩者皆非';return choice(level,variant,`A${fmt(a)} 與 B${fmt(b)} 的連線屬於哪一類？`,'只根據坐標判斷。',answer,['水平線','鉛垂線','兩者皆非'])}
 const a=point(-8,8,true),b=point(-8,8,true);if(variant%2===0)return numeric(level,variant,`P(${signed(a.x)}, □) 與 A${fmt(a)} 在同一水平線上。`,'求 □ 的值。',a.y,'',{hints:['水平線上各點的 y 坐標相同。','把 P 的 y 坐標寫成 A 的 y 坐標。']});return coordinate(level,variant,`標示同時與 A${fmt(a)} 在同一水平線，並與 B${fmt(b)} 在同一鉛垂線上的點 P。`,'點選格點，再檢查答案。',{x:b.x,y:a.y},'plot',{points:[{...a,label:'A'},{...b,label:'B'}],hints:['與 A 同一水平線，所以 y 坐標相同。','與 B 同一鉛垂線，所以 x 坐標相同。']})
}
function distance(level:number,variant:number){const horizontal=variant%2===0,a=point(-8,8,true);let delta=rand(1,Math.min(16,horizontal?16:16)),direction=variant%4<2?1:-1,b=horizontal?{x:a.x+direction*delta,y:a.y}:{x:a.x,y:a.y+direction*delta};while(Math.abs(b.x)>8||Math.abs(b.y)>8){delta=rand(1,8);direction*=-1;b=horizontal?{x:a.x+direction*delta,y:a.y}:{x:a.x,y:a.y+direction*delta}}
 if(level<2)return numeric(level,variant,`求 A${fmt(a)} 與 B${fmt(b)} 之間的距離。`,level===0?'參考坐標圖作答。':'不用繪圖，利用坐標之差計算。',delta,' 單位',{points:level===0?[{...a,label:'A'},{...b,label:'B'}]:undefined,segments:level===0?[{a,b}]:undefined,hints:[horizontal?'水平線段比較 x 坐標。':'鉛垂線段比較 y 坐標。','距離必須為正數，求兩個相關坐標之差。']});
 const start=point(-5,5,true),d=rand(1,3),dir=pick(['右','左','上','下']);const answer=dir==='右'?start.x+d:dir==='左'?start.x-d:dir==='上'?start.y+d:start.y-d;return numeric(level,variant,`點 B 位於 A${fmt(start)} 的${dir}方 ${d} 單位。`,`求 B 的${dir==='右'||dir==='左'?'x':'y'} 坐標。`,answer,'',{hints:[`由 A 向${dir}移動 ${d} 單位。`,dir==='右'||dir==='上'?'向右或向上時坐標增加。':'向左或向下時坐標減少。']})}
const polygonArea=(ps:Point[])=>Math.abs(ps.reduce((sum,p,i)=>{const q=ps[(i+1)%ps.length];return sum+p.x*q.y-p.y*q.x},0))/2;
function area(level:number,variant:number){
 if(level===0){const x=rand(-7,2),y=rand(-7,2),w=rand(2,6),h=variant%2===0?w:rand(2,6),ps=[{x,y},{x:x+w,y},{x:x+w,y:y+h},{x,y:y+h}];return numeric(level,variant,`求圖中${w===h?'正方形':'長方形'} ABCD 的面積。`,'先利用頂點坐標求長和闊。',w*h,' 平方單位',{polygon:ps,points:ps.map((p,i)=>({...p,label:'ABCD'[i]})),hints:['先以坐標之差求出兩條邊長。','面積＝長 × 闊。']})}
 if(level===1){const x=rand(-6,1),y=rand(-6,1),base=rand(2,7),height=rand(2,7),ps=[{x,y},{x:x+base,y},{x:variant%2?x:x+base,y:y+height}];return numeric(level,variant,'求圖中三角形 ABC 的面積。','底邊或高必須為水平或鉛垂線段。',base*height/2,' 平方單位',{polygon:ps,points:ps.map((p,i)=>({...p,label:'ABC'[i]})),hints:['先用坐標之差找出底和垂直高度。','三角形面積＝底 × 高 ÷ 2。']})}
 const templates:Point[][]=[[{x:0,y:0},{x:6,y:0},{x:6,y:2},{x:3,y:5},{x:0,y:2}],[{x:0,y:0},{x:7,y:0},{x:7,y:5},{x:4,y:5},{x:4,y:2},{x:0,y:2}],[{x:0,y:0},{x:6,y:0},{x:6,y:6},{x:4,y:3},{x:2,y:6},{x:0,y:6}]];const raw=templates[variant%templates.length],dx=rand(-7,1),dy=rand(-7,1),ps=raw.map(p=>({x:p.x+dx,y:p.y+dy})),method=variant<2?'分割法':variant<4?'補形法':'合適的方法';return numeric(level,variant,`利用${method}求多邊形的面積。`,'所有頂點均位於整數格點。',polygonArea(ps),' 平方單位',{polygon:ps,points:ps.map((p,i)=>({...p,label:String.fromCharCode(65+i)})),hints:[method==='補形法'?'先在外圍補成長方形。':'畫水平或鉛垂線，把圖形分成簡單圖形。','分別求簡單圖形面積，再作加法或減法。']})
}
function translation(level:number,variant:number){const p=point(-5,5,true),dx=level===2?(variant%2===0?rand(1,3):-rand(1,3)):level===0?(variant%2===0?rand(1,3):-rand(1,3)):0,dy=level===2?(variant%3===0?rand(1,3):-rand(1,3)):level===1?(variant%2===0?rand(1,3):-rand(1,3)):0,q={x:p.x+dx,y:p.y+dy},move=level===2?`${dx>0?'右':'左'} ${Math.abs(dx)} 單位，再向${dy>0?'上':'下'} ${Math.abs(dy)} 單位`:dx?`${dx>0?'右':'左'}平移 ${Math.abs(dx)} 單位`:`${dy>0?'上':'下'}平移 ${Math.abs(dy)} 單位`;return coordinate(level,variant,`點 P${fmt(p)} 先向${move}。`,'求影像 P′ 的坐標。',q,level===0?'plot':'text',{points:[{...p,label:'P'}],hints:[dx&&dy?'先分別處理 x 坐標和 y 坐標。':dx?'水平平移時 y 坐標不變。':'鉛垂平移時 x 坐標不變。','向右或向上坐標增加；向左或向下坐標減少。']})}
function reflection(level:number,variant:number){let p=point(-6,6,true),q:Point,axisLine:{axis:'x'|'y';value:number};if(level===0){q={x:p.x,y:-p.y};axisLine={axis:'y',value:0}}else if(level===1){const vertical=variant%2===0;q=vertical?{x:-p.x,y:p.y}:{x:p.x,y:-p.y};axisLine={axis:vertical?'x':'y',value:0}}else{const axis=variant%2===0?'x':'y',value=rand(-3,3)||2;axisLine={axis,value};q=axis==='x'?{x:2*value-p.x,y:p.y}:{x:p.x,y:2*value-p.y};while(Math.abs(q.x)>8||Math.abs(q.y)>8){p=point(-6,6,true);q=axis==='x'?{x:2*value-p.x,y:p.y}:{x:p.x,y:2*value-p.y}}}return coordinate(level,variant,`點 P${fmt(p)} 對${axisLine.axis==='x'?(axisLine.value===0?'y 軸':`直線 x＝${axisLine.value}`):(axisLine.value===0?'x 軸':`直線 y＝${axisLine.value}`)}反射。`,'求影像 P′ 的坐標。',q,level===0?'plot':'text',{points:[{...p,label:'P'}],axisLine,hints:['原像與影像到反射軸的垂直距離相同。','反射軸上的對應坐標是兩者的中點。']})}
function rotation(level:number,variant:number){const p=point(-6,6,true),turn=level===0?180:level===1?(variant%2===0?90:-90):pick([90,-90,180,270]),q=turn===180?{x:-p.x,y:-p.y}:turn===90||turn===-270?{x:-p.y,y:p.x}:{x:p.y,y:-p.x},label=turn===180?'180°':turn===90?'逆時針 90°':turn===-90?'順時針 90°':'逆時針 270°';return coordinate(level,variant,`點 P${fmt(p)} 繞原點${label}。`,'求影像 P′ 的坐標。',q,level===0?'plot':'text',{points:[{...p,label:'P'}],hints:['先判斷影像所在的象限。','90° 旋轉會交換兩個坐標的位置，並按方向改變正負號。']})}

function generate(game:GameId,level:number,variant:number):Question{if(game==='read-coordinates')return readCoordinates(level,variant);if(game==='plot-points')return plotPoints(level,variant);if(game==='quadrants')return quadrants(level,variant);if(game==='horizontal-vertical')return horizontalVertical(level,variant);if(game==='distance')return distance(level,variant);if(game==='area')return area(level,variant);if(game==='translation')return translation(level,variant);if(game==='reflection')return reflection(level,variant);return rotation(level,variant)}
export const questionKey=(q:Question)=>JSON.stringify({kind:q.kind,prompt:q.prompt,answer:q.answer,points:q.points,polygon:q.polygon});
export function makeQuestions(game:GameId,previous:Question[]=[]){const used=new Set(previous.map(questionKey)),out:Question[]=[];for(let level=0;level<3;level++){let attempts=0;while(out.length<(level+1)*5){if(++attempts>5000)throw new Error('未能產生足夠的不重複題目。');const q=generate(game,level,out.length-level*5),key=questionKey(q);if(!used.has(key)&&!out.some(item=>questionKey(item)===key)){used.add(key);out.push(q)}}}return[...shuffle(out.slice(0,5)),...shuffle(out.slice(5,10)),...shuffle(out.slice(10,15))]}
export function startSession(game:GameId,questions=makeQuestions(game),now=Date.now()):Session{return{game,questions,index:0,errors:0,stageErrors:0,firstTry:0,questionErrors:0,skipped:0,currentFirstTryStreak:0,longestFirstTryStreak:0,solved:false,finished:false,expired:false,feedback:'',startedAt:now,completedAt:null}}
function correct(s:Session,now:number){const finished=s.index===s.questions.length-1,first=s.questionErrors===0,streak=first?s.currentFirstTryStreak+1:0;return{...s,solved:true,finished,completedAt:finished?now:null,firstTry:s.firstTry+(first?1:0),currentFirstTryStreak:streak,longestFirstTryStreak:Math.max(s.longestFirstTryStreak,streak),feedback:`答對了！這題獲得 ${first?10:5} 分。`}}
function parseCoordinate(value:string){const match=value.trim().match(/^[（(]\s*([−-]?\d+)\s*[,，]\s*([−-]?\d+)\s*[)）]$/);return match?{x:Number(match[1].replace('−','-')),y:Number(match[2].replace('−','-'))}:null}
export function submit(s:Session,value:string,now=Date.now()):Session{if(s.finished||s.solved)return s;const q=s.questions[s.index];if(!value.trim())return{...s,feedback:'請先輸入或選擇答案。'};let ok=false,formatError=false;if(q.kind==='coordinate'){const parsed=q.input==='plot'&&/^-?\d+,-?\d+$/.test(value)?(()=>{const [x,y]=value.split(',').map(Number);return{x,y}})():parseCoordinate(value);formatError=!parsed;ok=Boolean(parsed&&parsed.x===q.answer.x&&parsed.y===q.answer.y)}else if(q.kind==='numeric'){const answer=Number(value);ok=Number.isFinite(answer)&&Math.abs(answer-q.answer)<1e-9}else ok=value===q.answer;if(ok)return correct(s,now);const errors=s.stageErrors+1,hint=s.game==='translation'&&q.level===2?'':q.hints[Math.min(errors-1,q.hints.length-1)];return{...s,errors:s.errors+1,questionErrors:s.questionErrors+1,stageErrors:errors,currentFirstTryStreak:0,feedback:formatError?'坐標格式不完整。請輸入括號、逗號和兩個坐標。':`再試一次。${hint}`}}
export function skipQuestion(s:Session,now=Date.now()):Session{if(s.finished||s.solved||s.index<10)return s;const finished=s.index===s.questions.length-1;return{...s,skipped:s.skipped+1,solved:true,finished,completedAt:finished?now:null,currentFirstTryStreak:0,feedback:'已放棄本題，這題不計分。'}}
export function expireSession(s:Session,now=Date.now()):Session{return s.finished?s:{...s,finished:true,expired:true,completedAt:now,feedback:'遊戲時間已達 1 小時，本局已結束。'}}
export const score=(s:Session)=>{const completed=s.index+(s.solved?1:0);return s.firstTry*10+Math.max(0,completed-s.firstTry-s.skipped)*5};
export const elapsedSeconds=(s:Session,now:number)=>Math.max(0,Math.floor(((s.completedAt??now)-s.startedAt)/1000));
export function nextQuestion(s:Session){return!s.solved||s.finished?s:{...s,index:s.index+1,stageErrors:0,questionErrors:0,solved:false,feedback:''}}
export type Action={type:'start';session:Session}|{type:'answer';value:string}|{type:'next'}|{type:'skip'}|{type:'timeout'}|{type:'home'};
export function reducer(s:Session|null,a:Action):Session|null{if(a.type==='home')return null;if(a.type==='start')return a.session;if(!s)return s;if(a.type==='answer')return submit(s,a.value);if(a.type==='skip')return skipQuestion(s);if(a.type==='timeout')return expireSession(s);return nextQuestion(s)}
