'use client';
/* oxlint-disable jsx-a11y/click-events-have-key-events, jsx-a11y/no-noninteractive-element-interactions, jsx-a11y/prefer-tag-over-role -- The SVG is a mathematical plot; pointer position is the answer and text-input alternatives are used elsewhere. */
import { useState } from 'react';
import { Check, Lightbulb } from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { Point, Question, Session } from '@/lib/game';

const MIN=-8,MAX=8,SIZE=360,PAD=24,STEP=(SIZE-PAD*2)/(MAX-MIN),sx=(x:number)=>PAD+(x-MIN)*STEP,sy=(y:number)=>SIZE-PAD-(y-MIN)*STEP;
function CoordinatePlane({question,selected,onSelect}:{question:Question;selected:Point|null;onSelect?:(point:Point)=>void}){
 const grid=Array.from({length:17},(_,i)=>i-8),points=question.points||[];
 const click=(event:React.MouseEvent<SVGSVGElement>)=>{if(!onSelect)return;const rect=event.currentTarget.getBoundingClientRect(),x=Math.round(MIN+(event.clientX-rect.left-PAD)/(rect.width/SIZE*STEP)),y=Math.round(MAX-(event.clientY-rect.top-PAD)/(rect.height/SIZE*STEP));if(x>=MIN&&x<=MAX&&y>=MIN&&y<=MAX)onSelect({x,y})};
 return <svg className="coordinate-plane" viewBox={`0 0 ${SIZE} ${SIZE}`} role="img" aria-label="直角坐標平面" onClick={click}>
  <rect x="0" y="0" width={SIZE} height={SIZE} className="plane-bg"/>
  {grid.map(n=><g key={n}><line x1={sx(n)} y1={sy(MIN)} x2={sx(n)} y2={sy(MAX)} className={n===0?'axis':'grid-line'}/><line x1={sx(MIN)} y1={sy(n)} x2={sx(MAX)} y2={sy(n)} className={n===0?'axis':'grid-line'}/>{n!==0&&<><text x={sx(n)} y={sy(0)+15} className="tick" textAnchor="middle">{n}</text><text x={sx(0)-8} y={sy(n)+4} className="tick" textAnchor="end">{n}</text></>}</g>)}
  {question.axisLine&&<line x1={question.axisLine.axis==='x'?sx(question.axisLine.value):sx(MIN)} y1={question.axisLine.axis==='y'?sy(question.axisLine.value):sy(MIN)} x2={question.axisLine.axis==='x'?sx(question.axisLine.value):sx(MAX)} y2={question.axisLine.axis==='y'?sy(question.axisLine.value):sy(MAX)} className="reflection-axis"/>}
  {question.polygon&&<polygon points={question.polygon.map(p=>`${sx(p.x)},${sy(p.y)}`).join(' ')} className="polygon"/>}
  {question.segments?.map((segment,i)=><line key={i} x1={sx(segment.a.x)} y1={sy(segment.a.y)} x2={sx(segment.b.x)} y2={sy(segment.b.y)} className="segment"/>)}
  {points.map((p,i)=><g key={`${p.x}-${p.y}-${i}`}><circle cx={sx(p.x)} cy={sy(p.y)} r="5" className="given-point"/><text x={sx(p.x)+8} y={sy(p.y)-8} className="point-label">{p.label}</text></g>)}
  {selected&&<g><circle cx={sx(selected.x)} cy={sy(selected.y)} r="8" className="selected-point"/><path d={`M${sx(selected.x)-11},${sy(selected.y)}h22M${sx(selected.x)},${sy(selected.y)-11}v22`} className="selected-cross"/></g>}
  <text x={SIZE-PAD+7} y={sy(0)-7} className="axis-label">x</text><text x={sx(0)+7} y={PAD-7} className="axis-label">y</text><text x={sx(0)-8} y={sy(0)+15} className="tick" textAnchor="end">O</text>
 </svg>
}
function CoordinateInput({onAnswer,disabled}:{onAnswer:(value:string)=>void;disabled:boolean}){const[value,setValue]=useState(''),keys=['(',')',',','1','2','3','4','5','6','7','8','9','−','0','back'];const add=(key:string)=>setValue(current=>key==='back'?current.slice(0,-1):current.length<18?current+key:current);return <form className="coordinate-answer" onSubmit={event=>{event.preventDefault();if(value&&!disabled)onAnswer(value)}}><label htmlFor="coordinate-answer">你的答案</label><input id="coordinate-answer" value={value} inputMode="text" autoComplete="off" placeholder="例如：(−3, 4)" disabled={disabled} readOnly/><div className="coordinate-keypad">{keys.map(key=><Button className="key" type="button" variant="secondary" key={key} disabled={disabled} aria-label={key==='back'?'刪除一位':key} onClick={()=>add(key)}>{key==='back'?'⌫':key}</Button>)}</div><Button className="block-btn" type="submit" disabled={!value||disabled}>檢查答案 <Check/></Button></form>}
function NumericInput({onAnswer,disabled,suffix}:{onAnswer:(value:string)=>void;disabled:boolean;suffix:string}){const[value,setValue]=useState(''),keys=['1','2','3','4','5','6','7','8','9','−','0','.','back'];const add=(key:string)=>setValue(current=>key==='back'?current.slice(0,-1):key==='−'?(current.startsWith('-')?current.slice(1):'-'+current):key==='.'&&current.includes('.')?current:current.length<8?current+key:current),valid=/^-?\d+(?:\.\d+)?$/.test(value);return <form className="numeric-answer" onSubmit={event=>{event.preventDefault();if(valid&&!disabled)onAnswer(value)}}><label htmlFor="numeric-answer">你的答案</label><div className="answer-with-unit"><input id="numeric-answer" value={value} inputMode="text" autoComplete="off" placeholder="輸入答案" disabled={disabled} readOnly/><span>{suffix}</span></div><div className="keypad coordinate-numeric-keypad">{keys.map(key=><Button className="key" type="button" variant="secondary" key={key} disabled={disabled} aria-label={key==='back'?'刪除一位':key} onClick={()=>add(key)}>{key==='back'?'⌫':key}</Button>)}</div><Button className="block-btn" type="submit" disabled={!valid||disabled}>檢查答案 <Check/></Button></form>}
function PlotInput({question,onAnswer,disabled}:{question:Question;onAnswer:(value:string)=>void;disabled:boolean}){const[selected,setSelected]=useState<Point|null>(null);return <div className="plot-answer"><CoordinatePlane question={question} selected={selected} onSelect={disabled?undefined:setSelected}/><Button className="block-btn" disabled={!selected||disabled} onClick={()=>selected&&onAnswer(`${selected.x},${selected.y}`)}>檢查答案 <Check/></Button></div>}
export default function GameBoard({session,answer,skip}:{session:Session;answer:(value:string)=>void;skip:()=>void}){const[planeHint,setPlaneHint]=useState(false);const q=session.questions[session.index],planeNeedsHint=(session.game==='translation'||session.game==='reflection')&&q.level>0&&session.index%5>=2,showPlane=Boolean(q.points||q.segments||q.polygon||q.axisLine)&&(!planeNeedsHint||planeHint);return <><div className="question-content"><span className="task-label">{session.index<5?'基礎':session.index<10?'核心':'綜合'}：{q.prompt}</span><p className="task-instruction">{q.instruction}</p><div className={showPlane&&!(q.kind==='coordinate'&&q.input==='plot')?'coordinate-layout':''}>{showPlane&&!(q.kind==='coordinate'&&q.input==='plot')&&<CoordinatePlane question={q} selected={null}/>}<div className="coordinate-controls">{planeNeedsHint&&!planeHint&&!session.solved&&<Button className="block-btn secondary" variant="secondary" onClick={()=>setPlaneHint(true)}><Lightbulb/>提示：顯示坐標平面</Button>}{q.kind==='coordinate'?(q.input==='plot'?<PlotInput question={q} onAnswer={answer} disabled={session.solved}/>:<CoordinateInput onAnswer={answer} disabled={session.solved}/>):q.kind==='numeric'?<NumericInput onAnswer={answer} disabled={session.solved} suffix={q.suffix}/>:<div className="answer-options coordinate-options">{q.choices.map(option=><Button className="block-btn choice" key={option} disabled={session.solved} onClick={()=>answer(option)}>{option}</Button>)}</div>}</div></div></div><output className={`feedback ${session.solved?'success':session.stageErrors?'hint':''}`} aria-live="polite">{session.feedback?<>{session.solved?<Check/>:<Lightbulb/>}<span>{session.feedback}</span></>:<span>慢慢想，準備好再作答。</span>}</output>{session.index>=10&&!session.solved&&<div className="give-up-wrap"><Button variant="ghost" className="give-up" title="放棄本題，不會增加錯答次數，但本題不會得分" onClick={skip}>放棄本題</Button></div>}</>}
